### ISSUE TITLE
delegate_method doesn't work with delegation to instance variables

### ISSUE THREAD

**Issue by ojab** [thoughtbot/shoulda-matchers#1005]
Looks like define_method matcher always checks delegation to method name, even if delegated method forwarded to instance variable
```ruby
require 'forwardable'

class PostOffice
  def deliver; end
end

class Courier
  extend Forwardable

  def_delegators :@post_office, :deliver

  def initialize
    @post_office = PostOffice.new
  end
end

describe Courier do
  it { should delegate_method(:deliver).to(:@post_office) }
end
```
produces
```
  1) Courier should delegate #deliver to #@post_office object
     Failure/Error: it { should delegate_method(:deliver).to(:@post_office) }

       Expected Courier to delegate #deliver to #@post_office object
       Method calls sent to Courier#@post_office: (none)
     # ./spec/xxx_spec.rb:21:in `block (2 levels) in <top (required)>'
```

**Comment by Looooong** [comment]
Also, it doesn't work with chained methods:

```ruby
delegate :foo, to: 'bar.baz'
```

**Comment by mcmire** [comment]
Hi @Looooong, can you make a new issue for that so it's easier to keep track of individual bugs?

**Comment by brunohkbx** [comment]
@mcmire I've been working on this issue but I couldn't find any way to expose the instance variables defined in the class to the singleton_class.

I could make this matcher `subject_has_delegate_object_reader_method?` pass by adding this conditional:
`subject.instance_variable_defined?(delegate_object_reader_method)`

However, I think there's no way to make the singleton_class access the instance_variable here:
https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/doublespeak/world.rb#L17

What do you think? :thinking:

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
