### ISSUE TITLE
[Feature request] validate_inclusion_of(:attribute).in{ dynamic_array_or_range }

### ISSUE THREAD

**Issue by Looooong** [thoughtbot/shoulda-matchers#1010]
In model, we can declare something like

```rails
validates :attribute, inclusion: { in: lambda { |record| dynamic_array_or_range } }
```

Perhaps, we should have a same thing to test that validation?

```rails
it { is_expected.to validate_inclusion_of(:attribute).in{ |record| dynamic_array_or_range } }
```

**Comment by mcmire** [comment]
I didn't know this was something you could do. I don't see why this shouldn't be possible.

**Comment by mcmire** [comment]
This looks like the same thing as the issue you just posted after this, #1011. Can I close this?

**Comment by Looooong** [comment]
#1011 is about an error when you use `inclusion` with association. It's not related to this one.

**Comment by mcmire** [comment]
Ah, my bad. I was thrown off by your example.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
