### ISSUE TITLE
Wording `allow_value` .. `with_message` does not read well

### ISSUE THREAD

**Issue by stowersjoshua** [thoughtbot/shoulda-matchers#1022]
The following usage of `allow_value` feels very strange to read:
```
it { is_expected.to allow_value('Suzuki').for(:brand).with_message('is out of business!') }
```
Everything makes sense up until `.with_message`. That method's argument is not used as some accompanying input to the value ('Suzuki'), instead it represents an expected response.

Perhaps we can alias `#with_message` with a clearer name? Maybe something like `#and_return`?
ie.
```
it { is_expected.to allow_value('Suzuki').for(:brand).and_return('is out of business!') }
```

It is important that one-liners be as readable as possible, and I feel like `allow_value` falls a little short in this example.

**Comment by mcmire** [comment]
Hey @stowersjoshua - sorry for the delay in responding. In maintaining this gem I've tried to stick to one principle. The qualifiers that validation matchers support generally correspond to actual options that the corresponding validations take. In other words, if you have an option in mind, you should be able to translate that to a qualifier fairly easily. In this case, `with_message` is an analog to the `message` option. Since all of the validations take this option, all of the validation matchers take 
this same qualifier. So while I agree with you that it is certainly important for specs to be readable, I wouldn't want to extend the API just for this one case -- I'd rather be consistent across the board.

You raise a good point, however: `allow_value` is kind of an odd duck -- it doesn't act like the other validation matchers. Instead of the matcher receiving an attribute, it receives a value. So what if we were to alias `with_message` to `with_failure_message` across the board and then change `allow_value` like this?

``` ruby
it { should validate_attribute(:brand).set_to("Suzuki").with_failure_message("is out of business") }
```

**Comment by stowersjoshua** [comment]
I'm glad we're in agreement.

Your solution is great!

It looks like you've got a lot in your backlog already. I can write up a PR for this if it would speed things up.

**Comment by mcmire** [comment]
@stowersjoshua That would be awesome 👍

**Comment by stowersjoshua** [comment]
I haven't been able to set aside time for this yet.
Something's come up and it may be a few weeks before I can contribute.
Let me know if you end up starting on this before then.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
