### ISSUE TITLE
Alternate method for testing PG array serialization

### ISSUE THREAD

**Issue by s2t2** [thoughtbot/shoulda-matchers#1024]
Some [recent](https://github.com/rails/rails/issues/29498) [guidance](https://github.com/rails/rails/pull/29520) from the rails community about using PostgreSQL array attributes instructs removal of `serialize(:my_array_attribute, Array)` from the model. As you would imagine, after removing that model code, the corresponding test, `it { should serialize(:my_array_attribute).as(Array) }`, fails.

Can you provide guidance on how to convert this test? I'd rather not remove it. And I'd prefer to keep using shoulda matcher syntax if possible, as it is very concise.

**Comment by mcmire** [comment]
Support for Postgres array columns is built into ActiveRecord, as you know. In fact, it's so seamless that you wouldn't notice it. The reason I say this is because if you attempted to write a test for this, it might look something like:

``` ruby
describe "some column" do
  it "converts Ruby arrays to Postgres arrays and back" do
    some_record = create(:some_model, my_column: [1, 2, 3])
    expect(some_record.my_column).to eq([1, 2, 3])
  end
end
```

Now, I would argue this is not a very meaningful test. And if you wanted to go lower than this, you'd be testing the same thing that Rails tests. So in my opinion, I don't think you need a test for an array column. But it's up to you, of course.
