### ISSUE TITLE
Validations blow up when setting subject to described class

### ISSUE THREAD

**Issue by lollar** [thoughtbot/shoulda-matchers#1029]
I typically write my specs by setting the `subject` to the class I'm writing specs for, like so:
```
Rspec.describe User, type: :model do
  subject { described_class }

  it { is_expected.to validate_presence_of(:username) }
end
```

It's just a personal style preference for my specs, however, when I do this and try to use the shoulda_matchers I get an error because shoulda_matchers is trying to set the attributes on `Class`. Like so: 
```
 NoMethodError:
       undefined method `username=' for #<Class:0x007ff38eef70c0>
```

I'm not sure if this is expected behavior or if it is something that should work. Either way I think it would be good to have it work or have it documented somewhere possibly. Let me know if I can help. Thanks.

**Comment by mcmire** [comment]
Hey @lollar. As you see, that's not a use case that we support. It turns out that this makes things a bit more difficult, because if we changed the matchers to support this, then they would have to know how to build instances of your model correctly. We can't just call `.new` on the class, though -- if your model has multiple validations on the same attribute, or custom validations, or something else that requires attributes to have specific values in order to pass validation, then the matcher would have to satisfy these requirements somehow, and it would take a lot of work to teach the matchers to infer how to do that. So it's a lot easier for us if we have you build your instances the way you want beforehand, since you probably know how to do that much better than the matcher would be able to.

I agree that this is something we should document in the README, since we do make the assumption that you haven't changed the `subject` like that. I'm curious if we need to add a Usage section to keep things organized -- that way we can have a place to include a note like that.

**Comment by lollar** [comment]
@mcmire Thanks for the quick reply.  That makes sense and was kind of what I was suspecting.  I'd be happy to take a run at creating a draft of something like a Usage section if you would like? Let me know.

Thanks.

**Comment by mcmire** [comment]
@lollar That'd be great!

**Comment by mcmire** [comment]
Sorry for the late reply on this. I finally updated the README if you want to take a look. ^

**Comment by lollar** [comment]
Looks great 🎉 appreciate it!
