### ISSUE TITLE
Improve performance of determine_where_to_break_line

### ISSUE THREAD

**Issue by betesh** [thoughtbot/shoulda-matchers#1041]
I have the following line of code in my model:

```
validates :content, length: { maximum: 20.megabytes }
```

and the following test:

```
it { should validate_length_of(:content).is_at_most(19.megabytes) }
```

The process hangs while it's generating the failure message.  Using a debugger, I traced it to this line:
https://github.com/thoughtbot/shoulda-matchers/blob/v3.1.2/lib/shoulda/matchers/util/word_wrap.rb#L194

When dealing with very long lines, we should limit how far we go trying to find some whitespace.

What do you think of changing this line from:

```
while line[index] !~ /\s/ && (0...line.length).cover?(index)
```

to:

```
line_length_or_reasonable_limit = [line.length, REASONABLE_LIMIT].min
while line[index] !~ /\s/ && (0...line_length_or_reasonable_limit).cover?(index)
```

and what would be the `REASONABLE_LIMIT` (I'm leaning towards 500)?

**Comment by mcmire** [comment]
Thanks for hunting this down, @betesh! It makes complete sense to limit the loop like that (I feel bad now that I didn't do this). We have tests for the word wrap code [here](https://github.com/thoughtbot/shoulda-matchers/blob/v3.1.2/spec/unit/shoulda/matchers/util/word_wrap_spec.rb). Would you implement the fix you described and write a test for it? I'll happily merge it in.

**Comment by betesh** [comment]
I took a different approach than I had originally expected.  It looks like rspec truncates the message, so the message being displayed is still incomplete.  I haven't tracked down the code that does that but I don't think it's in shoulda-matchers.

So I made just one change that addressed the performance issue here.  I think that's all we need to do here.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
