### ISSUE TITLE
have_one(:my_table).through(:polymorphic_connexion) failed

### ISSUE THREAD

**Issue by turgu1** [thoughtbot/shoulda-matchers#1044]
Hello,

In Rails 5.1.2, I have these tables defined:

```
class Allocation < ApplicationRecord
  belongs_to :consumer, polymorphic: true
  has_one :org, :through :consumer
  ...

class Person < ApplicationRecord
  has_many :allocations, as: :consumer, dependent: :destroy
  belongs_to :org, inverse_of: :people
  ...

class Requirement < ApplicationRecord
  has_many :allocations, as: :consumer, dependent: :destroy
  belongs_to :org, inverse_of: :requirements
  ...

class Org < ApplicationRecord
  has_many :people,       -> { order(:last_name, :first_name) }, dependent: :destroy
  has_many :requirements, -> { order(:project_name) }, dependent: :destroy
  ....
```

I'm trying to define a test like this:

```
require 'rails_helper'

RSpec.describe Allocation, type: :model do
  it { is_expected.to have_one(:org).through(:consumer) }
end
```

And I get the following error from running rspec:

```
NameError:
       uninitialized constant Allocation::Consumer
       .... shoulda-matchers-8d686d73644d/lib/shoulda/matchers/active_record/association_matcher.rb:1134:in 'rescue in class_exists?'
       .... shoulda-matchers-8d686d73644d/lib/shoulda/matchers/active_record/association_matcher.rb:1131:in 'class_exists?'
       .... shoulda-matchers-8d686d73644d/lib/shoulda/matchers/active_record/association_matcher.rb:991:in 'matches?'
```

Please advise if my expectations are too high ;-)

I've already several hundred tests using shoulda-matchers that are running well. This is a fantastic package!!!

Thanks for the help!

Guy T.

**Comment by mcmire** [comment]
Thanks for the report! This definitely seems like a bug. I'm not sure when we will get to it but I'll keep it here for now. :)

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
