### ISSUE TITLE
Ensure Ruby warnings that the gem emits are removed

### ISSUE THREAD

**Issue by lloeki** [thoughtbot/shoulda-matchers#1050]
When running tests on a project depending on shoulda-matchers some warnings are raised (see below).

This is because with a recent rake (>=11.0), ruby warnings are now on by default.

What do you think about fixing those warnings as well as running the test suite with ruby -w (which [seems to be the case](https://github.com/thoughtbot/shoulda-matchers/blob/2a5c312bcebf561d16577e3db57fbe111dae65df/Rakefile#L10)?) ?

```
/Users/lloeki/.gem/ruby/2.3.4/gems/shoulda-matchers-3.1.2/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:229: warning: method redefined; discarding old model
/Users/lloeki/.gem/ruby/2.3.4/gems/shoulda-matchers-3.1.2/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:149: warning: previous definition of model was here
```

**Comment by mcmire** [comment]
Yup, good point. We do run the test suite with warnings turned on, but they aren't surfaced in a way that only prints warnings related to shoulda-matchers and not other gems. Regardless, thanks for pointing this out -- we'll fix this.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
