### ISSUE TITLE
Did someone rewrite history on the rails-5 branch?

### ISSUE THREAD

**Issue by seven1m** [thoughtbot/shoulda-matchers#1055]
I was pointing to edaf9cb926ee9c59c59729e7a4f8c206b44da8a1 but that commit just disappeared. 😢

**Comment by consti** [comment]
@seven1m we've ran into the same issue here - missing she for us is f800d62525a65f9bf001ea984ae4926a92ff5b82; 😢

**Comment by guialbuk** [comment]
Hi, guys!

`rails-5` branch has been rebased onto `master`.

Pointing shoulda-matchers to `master` branch in Gemfile will fix it.

**Comment by mcmire** [comment]
Ah... sorry folks, that was my bad. It slipped my mind that we've made this branch sort of public. You can keep using the `rails-5` branch for your projects -- I'll refrain from doing this in the future.

**Comment by Carlows** [comment]
So, we should be pointing to master in Rails 5?

**Comment by guialbuk** [comment]
@Carlows Exactly. I will update the documentation about that.

And soon version 4.0 will be released.

**Comment by mcmire** [comment]
Well, `master` doesn't contain the fixes for Rails 5 -- those are all on the `rails-5` branch -- so using `master` won't get you those fixes.

That said, I do think we should merge `rails-5` into `master` and just remove the branch altogether. I'm generally not a fan of long-standing branches like this, and since we are focused on 4.0 there's no reason to keep two branches going. What do you think @guialbuk?

**Comment by mcmire** [comment]
I've gone ahead and merged `rails-5` into the master branch, as I think it makes sense going forward. That should make creating new PRs easier for folks too. I won't delete the branch, but now you really can switch to `master` and get the same fixes.
