### ISSUE TITLE
Validates uniqueness scoped on join table

### ISSUE THREAD

**Issue by rmaspero** [thoughtbot/shoulda-matchers#1083]
I have an accounts and a properties model, they are join via a join table called account_properties. The model for which I want to ensure am account can't create duplicate entires for themselves to a property. So I've got this validation in the model which appears to work from my testing.

```
class AccountProperty < ApplicationRecord
  belongs_to :property
  belongs_to :account

  validates_uniqueness_of :property, scope: :account
end
```

but when I describe it in the specs:

```
context 'validations' do
    it { is_expected.to validate_uniqueness_of(:property).scoped_to(:account) }
  end
```

I get the error

```
ActiveRecord::AssociationTypeMismatch:
       Property(#70276886662780) expected, got String(#70276872576580)
```

**Comment by mcmire** [comment]
Hey @rmaspero. I feel like this has been reported before, but the matcher doesn't support using associated objects as scopes like that. If it's possible to use `account_id` rather than `account`, then that should work.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
