### ISSUE TITLE
validate_length_of longtext column type gives range error

### ISSUE THREAD

**Issue by kashypat** [thoughtbot/shoulda-matchers#1085]
I have table called  "media_meta_data" and it has column "content" with "LONGTEXT" as datatype

I am trying to write specs for the media_meta_data model class
When this code executes
`  it { should validate_length_of(:content).is_at_most(4_294_967_295) }
`

It fails with following error
` Failure/Error: it { should validate_length_of(:content).is_at_most(4_294_967_295) }
     RangeError:
       integer 4294967296 too big to convert to 'int'`

Is there are way around it? I think this is bug in validate_length_of method.

**Comment by mcmire** [comment]
@kashypat Yeah that seems a bit weird. What's the backtrace?

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
