### ISSUE TITLE
validate_length_of doesn't work with numeric columns

### ISSUE THREAD

**Issue by bogdan8** [thoughtbot/shoulda-matchers#1094]
Hi, i have this validations
```
  validates :long_description, length: { minimum: 50 }
  validates :general_sum, length: { maximum: 6 }
```
And i have this rspec test
```
describe '#validations' do
    it { should validate_length_of(:long_description).is_at_least(50) }
    it { should validate_length_of(:general_sum).is_at_most(6) }
  end
```
test for minimum, works correct but on maximum i got this error:

```
    should validate that the length of :long_description is at least 50
    should validate that the length of :general_sum is at most 6 (FAILED - 1)

Failures:

  1) Initiative#validations should validate that the length of :general_sum is at most 6
     Failure/Error: it { should validate_length_of(:general_sum).is_at_most(6) }
     
       Initiative did not properly validate that the length of :general_sum is
       at most 6.
         After setting :general_sum to ‹"xxxxxxx"› -- which was read back as
         ‹0› -- the matcher expected the Initiative to be invalid, but it was
         valid instead.
     
         As indicated in the message above, :general_sum seems to be changing
         certain values as they are set, and this could have something to do
         with why this test is failing. If you've overridden the writer method
         for this attribute, then you may need to change it to make this test
         pass, or do something else entirely.
     # ./spec/models/initiative_spec.rb:38:in `block (3 levels) in <top (required)>'

```

What am i doing wrong? Thanks

**Comment by mcmire** [comment]
Hi @bogdan8,

`validate_length_of` is not intended to be used with numeric columns, only strings (because strings have `length`s). Does the length validation itself work with numeric columns?

**Comment by bogdan8** [comment]
Hi, @mcmire thanks for you response, 
"Does the length validation itself work with numeric columns?", yes
```
* General sum
333333333333333333333
is too long (maximum is 6 characters)
```
How can I check to validate the numeric field?

**Comment by mcmire** [comment]
@bogdan8 Hmm, interesting -- the length validator must have been updated at some point to support numeric columns: https://github.com/rails/rails/blob/2d672ea8ed05aa0a435b0a38ce7e292938f8a89b/activemodel/lib/active_model/validations/length.rb#L41

So unfortunately there's not a way to test this using shoulda-matchers. You'll have to write your own tests, I'm afraid.

**Comment by mcmire** [comment]
@Nimble-Momonga Can you create a separate issue for this? Thanks!

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
