### ISSUE TITLE
Suggestion on implicit behaviour of belong_to matcher

### ISSUE THREAD

**Issue by Looooong** [thoughtbot/shoulda-matchers#1108]
Currently, in Rails 5, the `belong_to` matcher will implicitly add a submatcher depends on the value of `ActiveRecord::Base.belongs_to_required_by_default`.

https://github.com/thoughtbot/shoulda-matchers/blob/c0960bd72dd41c4e9bd8b4375254f539776bfe95/lib/shoulda/matchers/active_record/association_matcher.rb#L971-L977

Take a look at this example:
```ruby
ActiveRecord::Base.belongs_to_required_by_default = false

class Post < ActiveRecord::Base
  belongs_to :user
  validates :user, presence: true
end

RSpec.describe Post, type: :model do
  it { is_expected.to belong_to(:user) }
end
```

The test will fail because of `optional` qualifier with a message like:
```bash
Expected Post to have a belongs_to association called user (the association should have been defined with `optional: true`, but was not)
```

I think that adding `optional` qualifier implicitly is inappropriate here.

The expected behaviour should be: if `belongs_to_required_by_default` is true, check if the association is required, otherwise do **nothing**.

My suggestion is that we should remove the `optional` part of the code.

**Comment by Looooong** [comment]
I will explain it further more. These are the cases:
+ If `required` is true or `optional` is false, there will always be a presence validator for that association.
+ If `required` is false or `optional` is true, Rails will not add a presence validator to that association, so basically, Rails does nothing. One of the following can happen:
  + We do nothing further more.
  + We add a presence validator.
  + We add a presence validator, with custom `if`/`unless` condition. (this is where `belong_to` matcher is broken, which I will explain later).

By saying that an association is optional,
+ it **doesn't** mean: that association is allowed to be `nil`.
+ it **does** mean: there won't be any presence validator that is active at any time.

I would also suggest that the `optional` qualifier not to check that the association is allowed to be `nil`, but to do one of the following:
+ Negate the `required` qualifier.
+ Check that the model doesn't have `valdiates_presence_of :association` without `if`/`unless` condition

---
## The special case where `belong_to` is broken

Here is the spec:

```ruby
require 'bundler/inline'
require 'rspec/autorun'
require 'rspec/core/formatters/progress_formatter'

gemfile true do
  source 'https://rubygems.org'
  gem 'activerecord', '~> 5.2.0' # which Active Record version?
  gem 'sqlite3'
  gem 'rspec-expectations'
  gem 'shoulda-matchers', github: 'thoughtbot/shoulda-matchers', ref: 'c0960bd72dd41c4e9bd8b4375254f539776bfe95'
end

require 'active_record'
require 'active_record/relation'

ActiveRecord::Base.belongs_to_required_by_default = false
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
  end

  create_table :posts, force: true do |t|
    t.references :user, index: true, foreign_key: true
  end
end

class User < ActiveRecord::Base
  has_many :fingerprint
end

class Post < ActiveRecord::Base
  attr_accessor :condition
  belongs_to :user
  validates :user, presence: true, if: :condition
end

Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    # Choose a test framework:
    with.test_framework :rspec

    # Choose one or more libraries:
    with.library :active_record
  end
end

RSpec.describe Post, type: :model do
  context 'when condition is false' do
    subject { Post.new condition: false }
    it { should belong_to(:user).optional } # Pass
  end

  context 'when condition is true' do
    subject { Post.new condition: true }
    it { should belong_to(:user) } # Fail
    it { should belong_to(:user).required } # Fail
  end
end
```

Test output:
```bash
.FF

Failures:

  1) Post when condition is true should belong to user optional: true
     Failure/Error: it { should belong_to(:user) } # Fail
       Expected Post to have a belongs_to association called user (the association should have been defined with `optional: true`, but was not)
     # test.rb:56:in `block (3 levels) in <main>'

  2) Post when condition is true should belong to user required: true
     Failure/Error: it { should belong_to(:user).required } # Fail
       Expected Post to have a belongs_to association called user (the association should have been defined with `required: true`, but was not)
     # test.rb:57:in `block (3 levels) in <main>'

Finished in 0.02699 seconds (files took 4.95 seconds to load)
3 examples, 2 failures

Failed examples:

rspec test.rb:56 # Post when condition is true should belong to user optional: true
rspec test.rb:57 # Post when condition is true should belong to user required: true
```

**Comment by cgriego** [comment]
The default requirement added when the matcher is initialized also breaks compatibility with Rails 4.2, because a Rails 4.2 association cannot be optional nor required, but an optional condition is added regardless.

**Comment by mcmire** [comment]
Hey guys, sorry for not replying sooner.

@Looooong, in response to what you said:

> By saying that an association is optional, it doesn't mean that association is allowed to be nil.

I see what you're saying, but this isn't quite accurate. If an association is not required, it _is_ by definition allowed to be nil. This is exactly the distinction that Rails 5 introduced by deprecating the `required` option and making `optional: false` the default. Associations have always been allowed to be nil in the past. Perhaps you didn't think about it, because that was the default (aside from setting `required: true`). But now that this distinction is important, and especially because the default is flipped, both alternatives should be tested in some way, in my opinion.

So I think the matcher is doing the right thing by mimicking the setting of `belongs_to_required_by_default`. However, I would agree with you that the error that the matcher gives isn't always appropriate in every scenario. Looking at your example again:

``` ruby
ActiveRecord::Base.belongs_to_required_by_default = false

class Post < ActiveRecord::Base
  belongs_to :user
  validates :user, presence: true
end

RSpec.describe Post, type: :model do
  it { is_expected.to belong_to(:user) }
end
```

I can see how an error like "the association should have been defined with `optional: true`, but was not" could be confusing, considering that that's not how you set up your association. What it really wants you to do, of course, is either remove the validation or add `.required` to the matcher, but that's not obvious based on the message.

In the second example, you have an instance of the same issue, but there _also_ seems to be a bug here with `.required`. It makes sense to me that the first test here would fail, but the second test _should_ pass:

``` ruby
context 'when condition is true' do
  subject { Post.new condition: true }
  it { should belong_to(:user) } # Fail
  it { should belong_to(:user).required } # Fail
end
```

So, I feel like there are two things going on here:

1. The messaging is potentially confusing, especially if you have a custom validation. I hope you agree; if not then I'm happy to discuss further.
2. Something is definitely going on with the `required` option in the case of a custom validation. We will definitely have to look into this further before releasing 4.0.

**Comment by mcmire** [comment]
@cgriego So I haven't tested out shoulda-matchers master on a Rails 4.2 app, so if you say that this is broken there, then I believe you, but my gut says this may be more of a messaging issue as well. Now that I look at this again, it probably doesn't make sense to default to `optional` on Rails 4.2 since associations don't have an `optional` option; it would probably make more sense to default to `required(false)` instead (that way if it fails, it'll say "the association should have been defined with `required: false` but was not"). I think I was trying to avoid checking against the Rails version specifically, since it basically doubles the tests, but it sounds like that's what we're going to have to do here.

**Comment by Looooong** [comment]
@mcmire The first thing in my mind when I posted this issue is that it will breaks a lot of tests that used to pass in version 3. Therefore, I suggest one of the following:
- Keep backward-compatibility with the previous version, but raise deprecation warning.
- Notify others about this breaking change in behaviour of the matchers.

Expand the message with suggestions will be good in both case.

About the bug, the sub-matchers doesn't seem to negate each other (like the combination of `.optional.required`), isn't it? If we can solve this bug, then the issue with implicit behaviour can be solved with explicit sub-matchers.

**Comment by Looooong** [comment]
@mcmire You should keep my first example as a reference, because that piece of code is what the test look like before `belongs_to_required_by_default` is a thing.

**Comment by mcmire** [comment]
@Looooong I thought about this some more and realized that I didn't quite understand what you were getting at and I completely agree with what you were saying. I came up with a PR that should hopefully solve this problem. Thank you for your examples -- I made sure to include them in the test suite.

**Comment by Looooong** [comment]
@mcmire After reviewing the PR, I think that you got the right idea. Good job :smile:
