### ISSUE TITLE
4.0.0.rc1 Release Tasks

### ISSUE THREAD

**Issue by guialbuk** [thoughtbot/shoulda-matchers#1111]
- [x] Generate documentation 6bd9118b568c4ebdc6430e74d70a800fb00ac7b0

- [x] Update NEWS.md with latest commits

- [x] Update README.md #1125

**Comment by mcmire** [comment]
Hey! Thanks for doing this. I left a comment on #904 but in case you didn't see it, I just wanted to make you aware of that before you pull the trigger on a proper release.

Also just an FYI since I didn't put this in the README: if you change the version in `version.rb`, you can run `rake docs:publish_latest` to generate and publish the docs to GitHub Pages using the new version. The `rake release` task will also generate/publish docs and push a new release, so there's that too.

**Comment by mcmire** [comment]
There's also #1108 as well. I guess apparently that's still broken.

**Comment by aried3r** [comment]
Awesome to see this! Is there anything I can do to help?

I'd like to propose to release a 4.0.0.beta1 or alpha, although I think it's at least beta quality, since I've been using the `master` branch for quite some time now.
That way people who want to update don't have to point to GitHub anymore and we have somewhat of a baseline people can report bugs on. Right now people might be pointing to different revisions, having different sets of bugs because of it. What do you think?

**Comment by composerinteralia** [comment]
@guialbuk Let me know if there anything you would like me to help with.

**Comment by yihyang** [comment]
Hi may I know what's the status of the release? Kinda hoped that this will get rolled up as soon as possible. Thanks.

**Comment by mcmire** [comment]
@guialbuk Hey! Thank you for continuing to be involved in this. I definitely don't want to include any more bugfixes in 4.0.0 than we already have planned. However, I am still concerned about two issues: #904 and, now, #1108. If we ship 4.0.0 with these issues still outstanding, I feel like a lot of people will be frustrated that we've released a broken version. If it was a minor point version then I wouldn't feel so bad, but since it's a major release it seems like we should try to get it right.

#1108 is easily fixable. #904, on the other hand, is a deeper, more fundamental issue that cuts across all of the matchers (or at least all of the validation matchers). I was very lost in it for a long time but lately I've picked it back up and I see the light at the end of the tunnel. However, of course, I know I haven't revealed _anything_ about it since I've been working on it, and I know you (and everyone else) is chomping at the bit to get something released. Let me email you about this when I get a chance and maybe we can talk about it more in detail? I feel like it requires some explanation.

**Comment by indocomsoft** [comment]
Yay, both #1108 and #904 are fixed now! :)

Does this mean that the release of 4.0.0 is imminent? 🎉

**Comment by guialbuk** [comment]
Hi @indocomsoft 
Yes! 😄 
We will release an RC version so everyone will have a chance to test some big changes made during the past weeks.
So 4.0 is coming very soon 🎉

**Comment by indocomsoft** [comment]
Any way I can help?

**Comment by guialbuk** [comment]
Hi @indocomsoft !

You can help in reviewing the documentation PRS, looking for typos or improvements:
https://github.com/thoughtbot/shoulda-matchers/milestone/13

Also using the gem in the current `master` branch helps a lot, as we had big code changes lately.

Thanks 😄

**Comment by guialbuk** [comment]
Fixed by #1125
