### ISSUE TITLE
4.0.0 rc1 breaks inclusion_of matchers with custom message

### ISSUE THREAD

**Issue by matthewrudy** [thoughtbot/shoulda-matchers#1146]
Here's the test which breaks

``` ruby
it do
  is_expected.to validate_inclusion_of(:gender).
    in_array(Forms::Detainee::GENDERS)
end
```

and here's the form code:

``` ruby
module Forms
  class Detainee < Forms::Base
    GENDERS = %w[male female unknown indeterminate].freeze
    validates :gender, inclusion: { in: GENDERS }
  end
end
```

And heres the test failure:

```
1) Forms::Detainee#validate should validate that :gender is either ‹"male"›, ‹"female"›, ‹"unknown"›, or ‹"indeterminate"›
     Failure/Error:
       is_expected.to validate_inclusion_of(:gender).
         in_array(Forms::Detainee::GENDERS) #.

       Expected detainee to validate that :gender is either ‹"male"›,
       ‹"female"›, ‹"unknown"›, or ‹"indeterminate"›, but this could not be
       proved.
         After setting :gender to ‹"shoulda-matchers test string"›, the matcher
         expected the detainee to be invalid and to produce the validation
         error "^Answer Gender" on :gender. The record was indeed invalid, but
         it produced these validation errors instead:

         * surname: ["^Enter a last name", "^Enter a last name", "^Enter a last
           name", "^Enter a last name", "^Enter a last name"]
         * forenames: ["^Enter first name(s)", "^Enter first name(s)", "^Enter
           first name(s)", "^Enter first name(s)", "^Enter first name(s)"]
         * date_of_birth: ["^Enter a valid date of birth", "^Enter a valid date
           of birth", "^Enter a valid date of birth", "^Enter a valid date of
           birth", "^Enter a valid date of birth"]
         * gender: ["^Choose a gender"]
     # ./spec/forms/detainee_spec.rb:40:in `block (3 levels) in <top (required)>'
```

importantly it is looking for the error message `^Answer Gender`
But we have a localised error message `^Choose a gender`

So I believe the issue is that it no longer asserts against the correct localised error message.

Relevant bits of our locale file:

``` yaml
en:
 errors: &errors
    messages:
      inclusion: "^Answer %{attribute}"
    models:
      detainee:
        attributes:
          gender:
            inclusion: "^Choose a gender"
```

I can fix the test by explicitly setting the expected message

``` ruby
it do
  is_expected.to validate_inclusion_of(:gender).
    in_array(Forms::Detainee::GENDERS).
    with_message(I18n.t('errors.models.detainee.attributes.gender.inclusion'))
end
```

however this seems wrong, as it worked before.

I did a (manual) git bisect,
and the error seems to be introduced in or around this commit

https://github.com/thoughtbot/shoulda-matchers/commit/507dc570047d671459b7d4b5e714972baffb2b3e

Thanks.

**Comment by indocomsoft** [comment]
@matthewrudy I tried fixing this issue with this branch: https://github.com/indocomsoft/shoulda-matchers/tree/fix-1146

Can you check whether it works?

**Comment by matthewrudy** [comment]
@indocomsoft that looks perfect, thanks.

To confirm, running off current master

``` ruby
gem 'shoulda-matchers', github: 'thoughtbot/shoulda-matchers', ref: 'e2154f9'
```

```
Finished in 0.96845 seconds (files took 8.13 seconds to load)
54 examples, 2 failures

Failed examples:

rspec ./spec/forms/detainee_spec.rb:39 # Forms::Detainee#validate should validate that :gender is either ‹"male"›, ‹"female"›, ‹"unknown"›, or ‹"indeterminate"›
rspec ./spec/forms/move_spec.rb:35 # Forms::Move#validate for not for release should validate that :not_for_release behaves like an optional field.
```

running off your branch

``` ruby
gem 'shoulda-matchers', github: 'indocomsoft/shoulda-matchers', ref: '441df05'
```

```
Finished in 0.92777 seconds (files took 8 seconds to load)
54 examples, 0 failures
```

Seems to be the right fix,
thanks very much.

👍

**Comment by mcmire** [comment]
@matthewrudy I'm revisiting this issue and there are a few things that stand out to me.

First, I think the previous version of the inclusion matcher had a hidden bug in it, where it didn't check to make sure that if the attribute was set to an invalid value it had an inclusion-related validation error message on it. The matcher didn't care which message was there, as long as the record was invalid in _some_ way. This could have easily led to false positives. So I am hesitant to roll back the commit that introduced this change, because I feel like the current behavior is more correct.

Second, I noticed that your `en.yml` may be incorrect. You have this:

```
en:
  errors: &errors
     messages:
       inclusion: "^Answer %{attribute}"
     models:
       detainee:
         attributes:
           gender:
             inclusion: "^Choose a gender"
```

According to the [Rails source code](https://github.com/rails/rails/blob/fc5dd0b85189811062c85520fd70de8389b55aeb/activemodel/lib/active_model/errors.rb#L407), when the inclusion validation fails, Rails will look for these i18n keys:

* `activemodel.errors.models.MODEL.attributes.ATTRIBUTE.inclusion`
* `activemodel.errors.models.MODEL.inclusion`
* `activemodel.errors.messages.inclusion`
* `errors.attributes.ATTRIBUTE.inclusion`
* `errors.messages.inclusion`

You have `errors.models.detainee.attributes.gender.inclusion`, but I think you should actually have `activemodel.errors.models.detainee.attributes.gender.inclusion`:

```
en:
  errors: &errors
     messages:
       inclusion: "^Answer %{attribute}"
     activemodel:
       models:
         detainee:
           attributes:
             gender:
               inclusion: "^Choose a gender"
```

That could possibly fix your issue.

Third, and finally, even if you had the correct key to begin with, I am a little perplexed as to how you got this issue in the first place. I wrote a failing test locally using your example and I couldn't replicate this at all (and still couldn't replicate it with `en.yml` corrected). I realize that @indocomsoft's fix above worked, but it really shouldn't have (as explained in my first point). The inclusion matcher uses the same logic as Rails to figure out which message to choose in `en.yml`, so the only thing I can think of is that maybe you're using a super old version of Rails? I will try again later using a fresh Rails app but for now I'm not sure how to fix this issue.
