### ISSUE TITLE
validate_confirmation_of checks error message against the wrong attribute

### ISSUE THREAD

**Issue by SzNagyMisu** [thoughtbot/shoulda-matchers#1156]
I work on a Rails 5.2 project. I test it with RSpec and use the shoulda-matchers for it. I am on the `rails-5` branch.

I wrote a test that the password should be confirmed,

```ruby
it { should validate_confirmation_of :password }
```

and it just didn't work. And I got this error message

```bash
Failure/Error: it { should validate_confirmation_of :password }
     
       User did not properly validate that :password_confirmation matches
       :password.
         After setting :password_confirmation to ‹"some value"›, then setting
         :password to ‹"different value"›, the matcher expected the User to be
         invalid and to produce the validation error "translation missing:
         hu.activerecord.errors.models.user.attributes.password.confirmation"
         on :password_confirmation. [...]
```

After a great deal of googling and trying I noticed something of an incoherence in the error message: it searched the error message of the attribute `:password` on the attribute `:password_confirmation`. When I added `rails-i18n` to my Gemfile and run `bundle install`, the test passed (`rails-i18n` provides the same confirmation error message for `:password` and `:password_confirmation`).

Digging into the source code I think I found the source of the problem:

```ruby
# lib/shoulda/matchers/active_model/validate_confirmation_of_mathcer.rb
# ValidateConfirmationOfMatcher#qualify_matcher
def qualify_matcher(matcher, confirmation_attribute_value)
  matcher.values_to_preset = {
    confirmation_attribute => confirmation_attribute_value
  }
  matcher.with_message(
    @expected_message,
    against: confirmation_attribute,
    values: { attribute: attribute }
  )
end
```

Here, if I'm not mistaken, the value of `values[:attribute]` is responsible for where to search the translation. If the line is changed to

```ruby
  values: { attribute: confirmation_attribute }
```

my test passes even if there is no available translation, or if the error message for `password.confirmation` is not the same as for `password_confirmation.confirmation`.

**Comment by mcmire** [comment]
@SzNagyMisu, thanks for the report, we'll look into this. I'm a bit wary of changing those `values` as you suggest especially since we haven't changed this matcher in a long time. But I also notice that we don't really have tests around the error messages that this matcher produces, so there could be a hidden bug here.

@guialbuk I'm going to remove this from the 4.0 release since it seems like this has existed for a while.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
