### ISSUE TITLE
Re installation for Rails 5.2

### ISSUE THREAD

**Issue by Russell108** [thoughtbot/shoulda-matchers#1157]
Hi I am on rails 5.2 & whatever I try I cannot seem to get these gems to work.

For example I added gems as follows
 gem 'shoulda', '~> 3.5'
   gem 'shoulda-matchers', '~> 2.0'

Then I get error
Error:
```
SubjectTest#test_invalid_without_name:
NoMethodError: undefined method `should' for #<SubjectTest:0x00007ff22cb6d818>
    test/models/subject_test.rb:17:in `block in <class:SubjectTest>'
```
Is there an uptown date installation for the latest matchers ?
If not how can I use 'shoulda-matchers' the latest version

**Comment by Russell108** [comment]
HI Elliot

I found another solution which I think seems to work

 gem "minitest-matchers_vaccine”

Thanks for the gems. Shoulda-matchers is saving me lots of time & effort & errors!!

Yes absolutely spend time on what’s essential 

Kind regards Russell

**Comment by mcmire** [comment]
@Russell108 Ah, okay, glad you found a solution! I keep forgetting that Minitest::Spec is essentially doing what Shoulda did before. That's pretty rad!

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
