### ISSUE TITLE
NameError: uninitialized constant Routing                                                                                                                              

### ISSUE THREAD

**Issue by sonalkr132** [thoughtbot/shoulda-matchers#1158]
I have following test:
```
class RoutingTest < ActionDispatch::IntegrationTest
    should route(:get, '/v1/test/hello').to('api/v1/test#hello')
end
```
in test_helper.rb
```
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :minitest
    with.library :rails
  end
end
```
On running test I get following:
```
NameError: uninitialized constant Routing                                                                                                                              
bin/rails test /home/aditya/.rvm/gems/ruby-2.3.5/gems/shoulda-context-1.2.2/lib/shoulda/context/context.rb:346                                                         
```

I am using should-matcher 3.2.1 and rails 5.2.1.1

**Comment by mcmire** [comment]
Try adding this to the top of your test class:

```
extend Shoulda::Matchers::Routing
```

**Comment by sonalkr132** [comment]
Doesn't help. I have tried all your suggestions on #953, including replacing [this](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/integrations/libraries/routing.rb#L15) with `ActionDispatch::IntegrationTest`.

**Comment by mcmire** [comment]
@sonalkr132 Can you provide me with a backtrace so I can see where this error is occurring?

**Comment by sonalkr132** [comment]
```
NameError: uninitialized constant Routing                                                                                                                              
bin/rails test /home/aditya/.rvm/gems/ruby-2.3.5/gems/shoulda-context-1.2.2/lib/shoulda/context/context.rb:346                                                         
```

is all of it.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
