### ISSUE TITLE
validate_numericality_of validation seem broken when upgrade Rails 5.2.3

### ISSUE THREAD

**Issue by yusuke-eto** [thoughtbot/shoulda-matchers#1199]
After upgrade Rails 5.2.3, I've found that `validate_numericality_of ` validation fail.
Probably because of this change
https://github.com/rails/rails/pull/32852

Ruby version: 2.3.8
Rails version: 5.2.3
shoulda-matchers gem version: 4.0.1
factory_bot gem version: 4.11.1
factory_bot_rails gem version: 4.11.1

**Comment by mcmire** [comment]
Hi, is this still an issue? Curious why you closed this.

**Comment by yusuke-eto** [comment]
@mcmire 
Sorry, I mistook close this.
Yes, this issue still happen.

**Comment by mcmire** [comment]
No worries. Can you give me a scenario that produces this bug?

**Comment by yusuke-eto** [comment]
After upgrading rails to 5.2.3, If i run following test, this bug happen.
I define balance decimal(16, 2).
```
require 'rails_helper'

describe Account, type: :model do
  describe 'validations' do
    it { is_expected.to validate_numerivality_of(:balance).is_greater_than_or_equal_to(-99_999_999_999_999.99).is_less_than_or_equal_to(99_999_999_999_999.99) }
  end
end
```

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
