### ISSUE TITLE
Have to manually include matchers

### ISSUE THREAD

**Issue by yourivdlans** [thoughtbot/shoulda-matchers#1203]
Hi!

Following this guide (https://github.com/thoughtbot/shoulda-matchers/wiki/Usage-with-standard-MiniTest-tests) I want to use Rails 6 and MiniTest.

I got it working but I still have to manually include the matchers I want to use for a test case.

I've created a gist with steps to reproduce this issue: https://gist.github.com/yourivdlans/2c6ec0bdfcf0c41d20a9e5dafaed7e04

Also I tried to use `gem 'shoulda-matchers', require: false` with `require 'shoulda/matchers` in my `test_helper.rb` to no avail.

Let me know if you need any more info :)

Thanks!

**Comment by mcmire** [comment]
@yourivdlans Keep in mind that the wiki is community-maintained, so it may not be as accurate as the official docs. 

Since you're making use of `shoulda-matchers` directly and not going through `shoulda`, you need to add a configuration block to your test_helper. See: https://github.com/thoughtbot/shoulda-matchers#rails-apps

**Comment by yourivdlans** [comment]
I see, thanks! This works :)

**Comment by mcmire** [comment]
No problem! Glad I could help.
