### ISSUE TITLE
validate_inclusion_of broken if other validations exist on the model

### ISSUE THREAD

**Issue by dvriezen** [thoughtbot/shoulda-matchers#1225]
When adding a validate_inclusion_of test the following error arises around other validations on the model that I am testing on. This was not the behaviour in 3.1.1. It should just be testing the inclusion validation and not be failing because other validations exist. 

```
After setting :worker_class to ‹"shoulda-matchers test string"›, the
         matcher expected the AsyncJob to be invalid and to produce the
         validation error "is not included in the list" on :worker_class. The
         record was indeed invalid, but it produced these validation errors
         instead:

         * owner: ["can't be blank"]
         * name: ["can't be blank"]
         * message: ["can't be blank"]
         * status: ["is not included in the list"]
```

The specific test I added was `it { should validate_inclusion_of(:status).in_array(['pending', 'running', 'canceled', 'completed', 'failed']) }` but it also failed on simpiler validate_inclusion_of tests I added with similar results.

**Comment by mcmire** [comment]
@dvriezen The validation messages on the other attributes are being shown for debugging reasons, but they are not actually making the test fail. The test is failing because it is expecting `worker_class` to be invalid by having "is not included in the list" as one of the error messages. This would lead me to believe that you're using `it { should validate_inclusion_of(:worker_class) }` somewhere. Is that not the case?

**Comment by dvriezen** [comment]
@mcmire oh, your comment lead me down the path to figure out what happened. It appears that with_message is required now if you have a custom message.

This breaking change wasn't in the changelog so I overlooked it at first.
