### ISSUE TITLE
Should the documentation suggest using the unreleased version of shoulda-context for Minitest users?

### ISSUE THREAD

**Issue by LunaCodeGirl** [thoughtbot/shoulda-matchers#1250]
> We're a bit behind in supporting Minitest at the moment. I don't think we even test that you can use controller matchers in an ActionDispatch::IntegrationTest (although in theory they should work).
> 
> I know the README advises staying on shoulda-matchers 2.x, but given that we are to 4.x now, what if you try upgrading? There's a pre-release version of shoulda-context out that should fix any compatibility issues. Instead of using this in your gemfile,
> 
> ```
> gem 'shoulda', '~> 3.5'
> gem 'shoulda-matchers', '~> 2.0'
> ```
> 
> try:
> 
> ```
> gem 'shoulda-context', '2.0.0.rc2'
> gem 'shoulda-matchers', '~> 4.0'
> ```
> 
> Then add the following to your `test_helper`:
> 
> ``` ruby
> Shoulda::Matchers.configure do |config|
>   config.integrate do |with|
>     with.test_framework :minitest
>     with.library :rails
>   end
> end
> ```
> 
> _Originally posted by @mcmire in https://github.com/thoughtbot/shoulda-matchers/issues/1247#issuecomment-542924409_

I noticed this comment in #1247. I went ahead and tried this myself and was able to start using the v4.1.2 matchers without issue. I'm using Minitest. I'm curious what's holding back support of minitest with shoulda-context? And even so, should the docs for shoulda-matchers be updated to suggest people use the above suggestion instead of such an old version of shoulda-mathers?

**Comment by LunaCodeGirl** [comment]
(Happy to make a PR, to do this, but figured I should ask around before assuming anything)

**Comment by mcmire** [comment]
For `shoulda-context`, nothing is really stopping a proper release, although I wanted to check it with existing projects to make sure I didn't break anything. I'm honestly not sure how many people still use it though, so maybe it's not a big deal. What I still have yet to do is wrap up some tests for `shoulda`, so that people can continue to use that instead of having to include `shoulda-context` and `shoulda-matchers` separately in their Gemfile. That said, I work on this in my free time and I don't get a lot of time to do this, so I can't say when that will be done. I would be fine with including some better and more up to date instructions in the README so that people aren't in limbo.

**Comment by mcmire** [comment]
I (finally) released Shoulda 4.0.0 and shoulda-context 2.0.0 today, which means I could also update the Minitest instructions in the README to match the RSpec instructions. So this should be fixed now!
