### ISSUE TITLE
Feature proposal: ActiveRecord Attributes matchers

### ISSUE THREAD

**Issue by Drenmi** [thoughtbot/shoulda-matchers#1285]
Hello! 👋 

I tried to search the open issues to see if this was already filed. Hopefully this won't be a duplicate.

### Background

With Rails 5, ActiveRecord introduced the new [Attributes API](https://blog.bigbinary.com/2018/12/11/rails-5-attributes-api.html).

### Proposal

I would like to be able to test that the correct attributes have been defined.

**Example:**

```ruby
it { is_expected.to define_attribute(:expires_on).as(:date).defaulting_to(Date.current) }
```

This interface was the first thing I thought of. It is not very well examined, and there might be better ideas. 🙂

**Comment by mcmire** [comment]
Hey @Drenmi! You're right, you're the first person to bring this up. So I have two immediate thoughts about this. The first is that in my experience, not many people use or even know about the Attributes API — even long-time Rails users. There are some people (I know this because this has happened at my job) who think that custom types add an unnecessary layer of complexity and that if you want to verify the format of a certain piece of data, validations are a simpler way to go. The other thought I have is that the Attributes API is naturally pretty open-ended. I mean, yes, given that ActiveRecord uses this API under the hood to create attributes in your model which are backed by columns — it's the reason why if you have a `datetime` column defined in your schema you can work with that column as a Time object — you can certainly re-use this API to create your own attributes that _aren't_ backed by columns. However you can also define your own types, and my hunch is that when people reach for the Attributes API, _this_ is really what they want to do and not merely re-use existing types. (Although it's entirely possible that people just want to use it to create fancy ActiveModel::Models as well.)

My point is that I don't have enough information to know whether a native matcher for the Attributes API would be something that people would use and whether it would be applicable across the board. I would be curious to know, how do you use the Attributes API, and what sort of tests do you write currently?

**Comment by Drenmi** [comment]
Hi, @mcmire!

I think your point is sound. 🙂 Let me elaborate a little on our use of the Attributes API. There are currently three use cases in our application.

1. As you mentioned, we have a single custom type. It is a `Duration` type that lets us put in and get out `ActiveSupport::Duration` objects (serialized to an integer representing the number of seconds) to and from the database. We use this for attributes like `processing_time`. For this we have tests for the type class itself only.

2. To set a default value for `Date` attributes (e.g. `transaction_date`) to `Date.current`. This is really a lot more concise than a `before_create` callback that conditionally assigns a value. This is also the use case where I was missing a shoulda-matcher. As a workaround I instantiate a record (bypassing the factory) and assert that the date is defaulted to the correct value.

3. Experimental: We have some virtual models in our applications, and we mimic the attributes declarations from ActiveRecord. People found this so convenient (no more searching in schema for attributes) that we are considering running an experiment to declare all attributes up front for database backed models, too.

I, like you, haven't seen much use of it in the wild, and the fact that I am the first to open this issue is even further proof that it hasn't seen widespread adoption. I am also not convinced by my own use of it that it should be a priority for shoulda-matchers. 😅

**Comment by mcmire** [comment]
I'm going to close this given your comments, but let me know if you or your team develops a pattern around this that might be useful in matcher form.
