### ISSUE TITLE
allow_value throwing error after Rails update

### ISSUE THREAD

**Issue by juniorjp** [thoughtbot/shoulda-matchers#1315]
Hi, I have my test like this:

```
    it { expect(subject).not_to allow_value("foo").for(:decimal) }
```

It was working on Rails 4.2, now I'm getting an error on Rails 5.0:

```
 ArgumentError: invalid value for BigDecimal(): "foo"
```

Also:
```
expect(subject).to validate_numericality_of(:decimal).is_greater_than_or_equal_to(0.01)
```

Now is throwing:
```
  ArgumentError: invalid value for BigDecimal(): "abcd"
```

Is there a new API for these cases?

**Comment by mcmire** [comment]
Hi @juniorjp. So this isn't shoulda-matchers doing, but this is due to fundamental changes that were made to ActiveRecord between Rails 4.2 and 5.0 which prohibit you from setting a numeric column to a non-numeric value. (You can read more about it here: https://github.com/rails/rails/pull/27429.) We've seen something like this issue before; [this commenter](https://github.com/thoughtbot/shoulda-matchers/issues/986#issuecomment-485468997) seems to indicate that a fix is available in Rails 5.0.5. Can you try that. Alternatively, is it possible to upgrade to Rails 5.1?

**Comment by juniorjp** [comment]
It worked upgrading to version 5.0.5 thank you!

**Comment by mcmire** [comment]
Woohoo! Glad you got it working.
