### ISSUE TITLE
`permit` matcher should be able to perform negative testing.

### ISSUE THREAD

**Issue by pgiblock** [thoughtbot/shoulda-matchers#1326]
shoulda-matchers-4.3.0
Strong parameters were introduced as a replacement for ActiveRecord protected attributes (`attr_accessible`). That is, a way to whitelist which attributes should be accepted (simply moved the concern from model to controller). The `permit` matcher does a good job ensuring that all expected parameters are permitted. However, it doesn't seem to support ensuring that unauthorized parameters are actually filtered. This, to me, is the more important test, as it prevents a client from setting arbitrary model attributes that were unintentionally permitted. 

I'll use some short hand to describe the various cases. In all test cases `@params = {good1: 1, good2: 2, bad1: 3}`.

### Normal case
Controller strong params are equal to Shoulda's permits.
```
params.permit(:good1, :good2)
```
```
should permit(:good1, :good2).for(:update, params: @params)
```
Result: PASS. This is expected.

### Controller is underly permissive
Controller strong params are a subset of Shoulda's permits.
```
params.permit(:good1)
```
```
should permit(:good1, :good2).for(:update, params: @params)
```
Result: FAIL. This is expected. Controller is not permitting a param specified in the test.

### Controller is overly permissive
Controller strong params are a superset of Shoulda's permits.
```
params.permit(:good1, :good2, :bad1)
```
```
should permit(:good1, :good2).for(:update, params: @params)
```
Result: PASS. This is unexpected. The point of strong parameters is to restrict parameters so they are not unintentionally passed into `#assign_attributes`, etc. This should be caught because the client could have done something evil. Maybe my expectation is philosophical, but see the next case...

### Explicit negative-testing doesn't work
Ok, maybe we need to manually perform positive and negative testing. Use `should_not` to test if bad parameters are accepted.
```
params.permit(:good1, :good2, :bad1)
```
```
should_not permit(:bad1).for(:update, params: @params)
```
RESULT: PASS. This test is explicitly saying "should not permit bad1". The controller permits it, yet the test passes. This should certainly be a failure.

----

Without some way to test this case, we cannot have an approximation of `should_not allow_mass_assignment_of` which, to me, is the more valuable test from a security standpoint. Ideally, what would be great is if `should_not permit(:bad1).for(:update, params: @params)` works intuitively. Secondly, it might be convenient to avoid two tests for every controller while still allowing folks to maintain the current `should permit` behavior. I'm requesting a `#exactly` method that can be used like `should permit(:good1, :good2).for(:update, params: @params).exactly`

**Comment by mcmire** [comment]
Hey @pgiblock, sorry for the delay in answering. I think you raised some valid issues but I wanted to make sure we are on the same page. 

First, you say "the point of strong parameters is to restrict parameters so they are not unintentionally passed into `#assign_attributes`, etc. This should be caught because the client could have done something evil." I fully agree with this, but it sounds there may be a misunderstanding about how the `permit` matcher works and I want to clear that up. The matcher does nothing to test that unpermitted parameters are stopped by your controller. That would be nice, but I think it would be unnecessary, because strong parameters are exclusionary by default — if you forget to permit something in your controller, then nothing bad happens, because it stops short anyway. All the matcher really does is test that you've called `permit` with the right arguments — or, as you've found out, the right _subset_ of arguments. As you allude to, this creates a philosophical situation. One could argue that the matcher only tests what you tell it to test — and as the developer it's your responsibility to make sure you are testing what needs to be tested.

It seems that the point you're making — and correct me if I'm wrong — has less to do with guaranteeing that the controller cannot receive parameters that are unknown and more to do with ensuring that developers are not permitting parameters they shouldn't (or, at the very least, ensuring that code and tests are in sync all the time). If you want to remove an existing parameter from the controller, and you are following test-first, if you take that parameter away from the test before you touch the controller, then the test will still pass. That definitely seems fishy, and I can see why you'd want some kind of exact check rather than a partial check. So, I think your `.exactly` idea makes a lot of sense here.

That leads me to your third example, the one with the negative test. It seems very odd to me that this wouldn't work:

```
params.permit(:good1, :good2, :bad1)
should_not permit(:bad1).for(:update, params: @params)
```

If the matcher treats the parameter list you provide as a subset of the real parameter list, then this test should not pass, because what you're saying is that you assert that this is not a subset. And yet, it is clearly a subset. So I'm very confused as to how you managed to make this fail. Would you be able to share more about this?

**Comment by mcmire** [comment]
I'm going to close this since it's gone a bit stale, but I'm happy to reopen if you want to continue the discussion!
