### ISSUE TITLE
Documentation on Shoulda Matchers site has incorrect id anchors

### ISSUE THREAD

**Issue by gee-forr** [thoughtbot/shoulda-matchers#1342]
Hi all,

Thank you for this wonderful lib - it really provides me such peace of mind that the basics are taken care of. Much appreciation :)

The [documentation on the main should site](http://matchers.shoulda.io/docs) has incorrect id anchor tags, and therefore they do not work at all. An example:

* ActiveModel::Matchers links to http://matchers.shoulda.io/docs/v4.3.0/#activemodel-matchers
* The actual ActiveModel::Matchers section is identified with `#ActiveModel_matchers` and not `#activemodel-matchers`
* All sections pretty much have this problem.

I've searched through the other issues here, and can't find anything referencing this issue, so I hope I haven't opened a duplicate.

I would love to issue a PR to fix this, but I honestly wouldn't know where to start. If one of the resident giant robots patrolling this repo could give me a few pointers, I'll fix the issue.

Thanks :)

**Comment by KapilSachdev** [comment]
Looks like there are two table of contents on the page, one hidden with correct anchor and id links and another which is visible with wrong ones.

Readme uses markdown and the repo generates documentation using yard.

There are known issues with yard and markdown being incompatible and links are the one of the incompatibility.

I think what  @mcmire tried was to counter that incompatibility by generating the TOC (and much more in `app.js`)

https://github.com/thoughtbot/shoulda-matchers/blob/43cdc247040ab2562d25fb3e506dfd4d5e636a6b/doc_config/yard/templates/default/fulldoc/html/js/app.js#L183

 and hide the TOC that is generated by markdown and create one for yard.

https://github.com/thoughtbot/shoulda-matchers/blob/43cdc247040ab2562d25fb3e506dfd4d5e636a6b/doc_config/yard/templates/default/fulldoc/html/js/app.js#L222

But the intended didn;t happened or stopped happening.

_This is my understanding going though app.js and might be wrong_

I think you will be able to fix this by modifying app.js.

**Comment by mcmire** [comment]
Thanks for looking into that @KapilSachdev. It's been a long time since I wrote `app.js` and I'm having trouble remembering what my intent was for `generateTOC`, although clearly, it doesn't do anything, otherwise I imagine you'd see a sidebar or something (perhaps it's disabled on certain pages).

It's true that we use YARD to generate documentation. YARD has the ability to convert Markdown into HTML, but unfortunately it doesn't do this in the same way that GitHub does. Specifically, it doesn't add anchors at all to headers. I think that's the real issue here and I wonder if a more direct solution would be to switch to another Markdown library that can automatically do this. At the moment we are using Redcarpet; I believe Kramdown does this by default, although I am open to other libraries (provided they don't add an anchor link to the right of the header, which could create undesirable behavior for docstrings themselves, which also get passed through Markdown).

**Comment by mcmire** [comment]
Just looked again at YARD and it looks like 0.9.25 includes an update to Redcarpet which adds ids to the headers. It may be a good idea to investigate that: https://github.com/lsegal/yard/blob/main/CHANGELOG.md#0925---may-3rd-2020.

**Comment by KapilSachdev** [comment]
Yes, it fixes the issue reported.
One more interesting change.
Before update
```bash
Files:         126
Modules:        26 (   26 undocumented)
Classes:        56 (   56 undocumented)
Constants:      12 (   12 undocumented)
Attributes:     58 (    0 undocumented)
Methods:       416 (  405 undocumented)
 12.15% documented
```

After upgrade
```
Files:          41
Modules:         6 (    2 undocumented)
Classes:         0 (    0 undocumented)
Constants:       0 (    0 undocumented)
Attributes:      0 (    0 undocumented)
Methods:        46 (    8 undocumented)
 80.77% documented
```

**Comment by mcmire** [comment]
@KapilSachdev Yeah, I'm not sure what they changed in YARD, but whatever it was, it works much better now 👍

**Comment by gee-forr** [comment]
Nice - thanks so much all :)
