### ISSUE TITLE
should belong_to required_matcher uses invalid objects

### ISSUE THREAD

**Issue by sonalkr132** [thoughtbot/shoulda-matchers#1375]
Hi, we are having a hard time updating to v4 as some of our `should belong_to` tests are failing. A few of them were legitimate failures and I have fixed them. However, there are others where failure seem avoidable to me. Consider the following relation and validation on Dependency model:

```
belongs_to :rubygem, optional: true
belongs_to :versions
before_validation :use_gem_dependency
```
I am getting `Dependency should belong to version required: true` for `should belong_to :version`. As you may be able to tell, the versions relation is already `require: true` (rails 5 default). On some [puts debugging](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_record/association_matchers/required_matcher.rb#L23) I am noticing that all attributes of Dependency are set to nil and `gem_dependency` (attr accessor of Dependency) doesn't exist and hence the `use_gem_dependency` is failing:
```
# puts subject
...
@record=#<Dependency id: nil, requirements: nil, created_at: nil, updated_at: nil, rubygem_id: nil, version_id: nil,
scope: nil, unresolved_name: nil>, @attribute=:rubygem, @context=nil, @expects_strict=false, @expected_message=nil, @_validation_result={:all_validation_errors=>#<ActiveModel::Errors:0x0000559a76c797d0 @base=#<Dependency id
: nil, requirements: nil, created_at: nil, updated_at: nil, rubygem_id: nil, version_id: nil, scope: nil, unresolved_name: nil>, @messages={:rubygem=>
["Please use Gem::Dependency to specify dependencies."]}, @details={:rubygem=>[{:error=>"Please use Gem::Dependency to specify dependencies."}]}>, :va
lidation_error_messages=>["Please use Gem::Dependency to specify dependencies."], :validation_exception_message=>nil}, @captured_validation_exception=
false, @captured_range_error=false>>
```

Why are we not using factories we have set up and only setting attribute we are testing to nil? In the above example, only `version` should be nil.

Related: https://github.com/rubygems/rubygems.org/pull/2408

**Comment by mcmire** [comment]
Hey @sonalkr132. So I don't see any factories being used in your test. You're just using `should belong_to(...)` straight away which means that by default the `subject` will be a blank Dependency object. If you're thrown off by the fact that `use_gem_dependency` is failing, I think that's okay — shoulda-matchers doesn't care about messages that appear on other attributes, only the one that you're currently testing. So that in itself should not be causing your test to fail.

What is the error message you're getting when you run your test?

**Comment by sonalkr132** [comment]
I am seeing the following in the failure message ([build link](https://travis-ci.org/github/rubygems/rubygems.org/jobs/742355602#L682)):
```
Failure:
DependencyTest#test_: Dependency should belong to version required: true.  [/home/travis/build/rubygems/rubygems.org/vendor/bundle/ruby/2.6.0/gems/shoulda-context-2.0.0/lib/shoulda/context/context.rb:62]:
Expected Dependency to have a belongs_to association called version (and for the record to fail validation if :version is unset; i.e., either the association should have been defined with `required: true`, or there should be a presence validation on :version)
```
This seems a bit unexpected given that we are [using `belong_to :version`](https://github.com/rubygems/rubygems.org/blob/master/app/models/dependency.rb#L3)

I am not exactly familiar with how `should belong_to :version` is supposed to set up the subject. all attributes being `nil` felt a bit weird, hence I pointed it out.

Consider another failure, this one an error:
```
Error:
DeletionTest#test_: Deletion should belong to user required: true. :
NoMethodError: undefined method `rubygem' for nil:NilClass
    app/models/deletion.rb:30:in `rubygem_name'
    app/models/deletion.rb:34:in `record_metadata'
```
The test is for `should belong_to :user`, however since the version accessor is nil, `before_validation` is blowing up.
I suppose it can also be possible that until v4 shoulda-matchers was not running the hooks, hence tests were passing. Definitely related to: 
> Add required and optional qualifiers to belong_to and have_one matchers. (When using the belong_to matcher under Rails 5+, required is assumed unless overridden.)`

**Comment by mcmire** [comment]
Okay, so I just tried pulling down your branch and running the tests myself. It seems that there are a couple of things happening here.

With regard to how `should belongs_to :version` sets up your subject, the answer is that it doesn't do a lot. The way that our matchers work in general, especially ones that involve testing validations, is that they're really only concerned with the attribute that you're testing — no other attribute is changed. So since the default subject is a Dependency object where everything is nil, that's where it begins, and then it will manipulate `version` as needed. In this case, since the `belong_to` matcher is implicitly testing that a presence validation is on `version`, it will set `version` to nil and confirm that a validation error shows up on `version` (thereby testing `required: true`).

What `belong_to` is trying to do in testing the presence validation, however, is being thwarted by the fact that `rubygem` is not set (as you alluded to). This creates a problem because you have a validation in Dependency which will `throw :abort` if that is the case. I am a little unfamiliar with this as I don't see it a lot, but I believe that this stops the validation chain entirely. So, even though that you're presently concerned with testing `version`, everything is actually dependent on `rubygem` being set correctly, since it is being checked in a `before_validation`.

To fix this issue, I would recommend overriding `subject` somewhere in your test case that sets `rubygem` to a meaningful value (in fact, it's also worth it to set any other attributes that have constraints or validations on them to meaningful values). You can either choose to do this at the top of the class or you can place both of your `belong_to` lines in a context and then override the subject in that context.

If you do not wish to do this, you may add `.without_validating_presence` to `belong_to` like so:

``` ruby
should belong_to(:version).without_validating_presence
```

and that will tell `belong_to` not to run validations, thereby bypassing this issue. Although note that this may be a bit of a landmine for others in the future, so it's your call.

**Comment by sonalkr132** [comment]
Thank you for taking the time to debug this.

> This creates a problem because you have a validation in Dependency which will throw :abort if that is the case. 
> To fix this issue, I would recommend overriding subject somewhere in your test case that sets rubygem to a meaningful value

I guess this makes sense. I have set the subject on failing tests and it seems to be working. I agree these hooks are a bit wonky and we are depending/testing for the record being valid in a `before_validation` hook. Still interesting that no one else has tripped over this yet.

While I am here, allow me to bring this up https://github.com/rubygems/rubygems.org/pull/2243. can you please take a few minutes to give your two cents (with a comment on PR please)? Particularly what may be the downsides of going ahead with that. As far as I can tell `should belongs_to` tests are basically checking if the schema was set up correctly (besides the required qualifiers tests we added recently).

**Comment by mcmire** [comment]
@sonalkr132 Done!
