### ISSUE TITLE
Add `allow_blank` for `validate_presence_of` 

### ISSUE THREAD

**Issue by sshaw** [thoughtbot/shoulda-matchers#1407]
Hi, sounds odd but all validators support `:allow_nil` and `:allow_blank` and there are cases where the column is not null but empty strings are fine. 

Also when one has not null `hstore` or `jsonb` column (PostgreSQL) with a default value of `'{}'::jsonb`, one must set `:allow_blank => true` otherwise these saving will fail since `{}.present?` is `false`. 

Thoughts?

**Comment by mcmire** [comment]
Sounds reasonable. I think it is so rare that it hasn't come up yet, so that is why we don't support it, but we would gladly take a PR :) If you want to take this on and need help let me know.

**Comment by sshaw** [comment]
Yeah I can do something but was on the Rails 5.2.X codebase in question a few days ago and the use of `:allow_blank` + `:allow_nil` did not work. Maybe this is why it does not exist here.

I will check on a later version of Rails and get to you (but feel free to harass me if I don't!)

PS SuperDiff 💪

**Comment by Shaglock** [comment]
Hello @sshaw! I have the same issue as you, do you have any news\progress on PR maybe?

**Comment by billr578** [comment]
It looks to me like the validation_matcher class has support for `allow_blank`, however, rspec raises an error from line 28:

`NoMethodError:
       undefined method `[]=' for nil:NilClass`

I think that's because `options` never gets initialized and we're trying to set a hash value on a nil object.  I'm happy to be wrong though and I'm just not using this matcher properly.  :)
