### ISSUE TITLE
allow_value not handling aliased attributes

### ISSUE THREAD

**Issue by rubendinho** [thoughtbot/shoulda-matchers#1460]
I am running into problems using `allow_value` with an alias attribute.  

This is my model, which has a column called `custom_data`, aliased as `metadata`.  

```
class Widget < ApplicationRecord
  alias_attribute :metadata, :custom_data
  validates :metadata, presence: true, allow_nil: true
  ...
end
```

In my tests, using the `allow_value` is not working as expected with the original column name `custom_data`. 

✅ `expect(Widget.new).not_to allow_value("").for(:metadata)` passes as expected. 
🔴 `expect(Widget.new).not_to allow_value("").for(:custom_data)` fails with:
>RSpec::Expectations::ExpectationNotMetError: After setting :custom_data to ‹""›, the matcher expected the Widget to be invalid, but it was valid instead.

This seems like a bug because the record `Widget.new(metadata: "").invalid?` and `Widget.new(custom_data: "").invalid?` will both evaluate to `true`.  

Other matchers like`validate_presence_of`, are respecting the alias, as expected:
✅ `it { expect(Widget.new).to validate_presence_of(:metadata).allow_nil }`
✅ `it { expect(Widget.new).to validate_presence_of(:custom_data).allow_nil }`

I am running Rails 6.1, with v5.0.0 of the gem (same issue with v4.5.1)

**Comment by EduardoSCosta** [comment]
I was investigating this issue and found that the same thing happens with other matchers (like validate_presence_of and validate_numericality_of). And it only validates the attribute present in `validates :attribute_name` regardless of whether it is the original attribute name or its alias.

I really don't know if this behaviour is intentional or not, it would be cool if a maintainer could clarify this.

**Comment by mcmire** [comment]
Hi @EduardoSCosta. It's not intentional, it's just something we've never addressed. A PR to fix this would be greatly appreciated!

**Comment by EduardoSCosta** [comment]
Interesting @novotarq , I'll take a look at it

**Comment by mcmire** [comment]
> I think it is more an issue in Rails, where it does not provide an error for `custom_data`

That makes sense! If you have `validates :metadata, presence: true` in your model, the presence validator will put the validation error on your `metadata` attribute, not `custom_data`.

> On the code side, my proposed solution would be to add a lookup in `AllowValueMatcher#for` with a check whether an alias is being used.

Ah! So, I thought about this a bit more and realized that we already have something which sort of solves this problem. The `with_message` qualifier on `allow_value` lets you specify the attribute that holds the error, so you could say:

```
expect(Widget.new)
  .not_to allow_value("")
  .for(:custom_data)
  .with_message("some error message", against: :metadata)
```

Now, this is a bit unwieldy because it requires you to provide the error message in the test, when that may not matter. It would be great if you could drop the message:

```
expect(Widget.new)
  .not_to allow_value("")
  .for(:custom_data)
  .with_message(against: :metadata)
```

But for now you would have to use the above.

Does that solve your problem?

**Comment by novotarq** [comment]
I'm not sure if it solves @rubendinho's problem, but works great on my side!

However, I think that
```
expect(Widget.new)
  .not_to allow_value("")
  .for(:custom_data)
  .against(:metadata)
```
would be a bit less confusing.

What do you think?

**Comment by EduardoSCosta** [comment]
I tried to implement the `.against` method in `allow_value_matcher` and it seems to have worked very well, if you decide to go that route I can create the specs and open a PR.

**Comment by mcmire** [comment]
@EduardoSCosta Sure! I think that adding an explicit `.against` method makes sense.
