### ISSUE TITLE
Shoulda Matchers for Python

### ISSUE THREAD

**Issue by s2t2** [thoughtbot/shoulda-matchers#1494]
Hi, I loved using shoulda matchers in my rails apps, but have been using flask apps in Python more recently, and testing them with pytest.

Are you aware of any current python ports of the shoulda matchers functionality? Or are there potentially any plans to create one?

Thanks!

**Comment by mcmire** [comment]
Hi @s2t2, we have no plans to create a version of shoulda-matchers that is suited for Flask. I am not a Pythonista, but I believe that pytest works differently than RSpec and is closer to Minitest than RSpec, so I expect you might be looking for a set of assertions? I don't know if Flask has built-in test assertions but I see that Django has some [here](https://docs.djangoproject.com/en/4.0/topics/testing/tools/#assertions) and are made available through this pytest plugin for Django [here](https://pytest-django.readthedocs.io/en/latest/helpers.html#assertions), so maybe you could use this as inspiration? There is also a Flask plugin for pytest [here](https://pytest-flask.readthedocs.io/en/latest/), but it seems to be mostly focused on setting up fixtures and doesn't provide assertions, so I'm not sure if that's of use. I don't know if this is because people don't feel like they need custom assertions when testing Flask applications or whether they haven't tried. Maybe it's worth asking more about this in a Python community. Sorry I couldn't be more helpful.
