### ISSUE TITLE
Add :uniq => true support

### ISSUE THREAD

**Issue by karlingen** [thoughtbot/shoulda-matchers#477]
:uniq
http://apidock.com/rails/v3.2.8/ActiveRecord/Associations/ClassMethods/has_many
If true, duplicates will be omitted from the collection. Useful in conjunction with :through.

**Comment by aried3r** [comment]
Sorry for bringing this up again, but I wasn't able to find this in the current release or RC, is there a different way to test `has_many :things, -> { uniq }` other than manually?

**Comment by maurogeorge** [comment]
@aried3r take a look on the [conditions of the have_many](http://matchers.shoulda.io/docs/v2.8.0/Shoulda/Matchers/ActiveRecord.html#have_many-instance_method).

Could you try something like this:

```ruby
it { should have_many(:things).conditions(uniq: true) }
```

**Comment by mcmire** [comment]
Unfortunately right now, there's not a way to do this, no. `conditions` won't work because `uniq` isn't a part of the WHERE clause. You'd have to write a custom test in that case.

**Comment by aried3r** [comment]
Ok, thank you!

**Comment by aried3r** [comment]
Can we re-open this issue?

**Comment by mcmire** [comment]
I don't plan on working on this any time soon. What would opening the issue provide?

**Comment by aried3r** [comment]
Depends, do you see open issues as a TODO list, even for possible future features?

**Comment by mcmire** [comment]
Sort of. I tend to leave an issue open if it's a bug, because those take priority over features, and I feel like it's important to indicate that I am definitely working on them. I'm really the only maintainer of this gem, and as it turns out, I don't have much time to work on anything but bugs these days, so leaving feature issues open would convey somewhat of a false hope. There are already plenty of bug issues open and I feel like keeping features open as well would only add to the number of open issues overall, and you'd see issues that were open for a really long time without any activity. All this to say, it's often faster if someone from the community picks up the work, because that means I don't have to do so much work to add it.

In the off chance that someone at thoughtbot wants to work on this gem, I do keep an internal list of all features -- and they're tagged with Feature on here anyway, so they're easy to find should the need arise.
