### ISSUE TITLE
Possible to test the options on a before_filter?

### ISSUE THREAD

**Issue by mattcl** [thoughtbot/shoulda-matchers#559]
I was hoping to do something like 

``` ruby
it { should use_before_filter(:foo).only(:bar, :baz) }
```

Is there any plan to support this on the action controller callback matchers?

**Comment by saghaulor** [comment]
It's odd that this is acknowledged as a thing to do, and this issue was closed. Are there any recommended work arounds?

**Comment by mcmire** [comment]
We prefer to close issues for feature requests if it's something that we know we won't get to soon. We don't want to clutter up the issues list with long-standing issues -- we already have plenty of issues open for bugs already. If it's something someone is interested in we are glad to take a PR. Regardless, we have a note of it internally, so it's recorded somewhere at least. 

As for a workaround, you could try using a mocking library to assert that a method is called on the controller in example groups that involve the corresponding actions. In other words, if your controller looked like this:

``` ruby
class FooController < ApplicationController
  before_action :foo, only: [:bar, :baz]

  def bar
    ...
  end

  def baz
    ...
  end

  private

  def foo
    ...
  end
end
```

you could test it like so:

``` ruby
describe FooController do
  describe "GET #bar" do
    allow(controller).to receive(:foo)
    get :bar
    expect(controller).to have_received(:foo)
  end

  describe "GET #baz" do
    allow(controller).to receive(:foo)
    get :baz
    expect(controller).to have_received(:foo)
  end
end
```

Now, I honestly think this is a bit of a code smell, since you're making assertions on a private method inside of the controller. So one thing I would suggest doing is testing your `before_action` manually (using a shared example group or something so you're not repeating yourself, perhaps). But that's up to you.
