### ISSUE TITLE
validate_numericality_of should use a string as an out-of-bounds value, not an integer

### ISSUE THREAD

**Issue by abitdodgy** [thoughtbot/shoulda-matchers#575]
I don't know if this is by design or if it's a bug. But I keep getting a failure when using a before validation callback.

```
Finished in 2.931728s, 52.5287 runs/s, 67.5370 assertions/s.

  1) Failure:
AddressTest#test_: Address should ensure post_code has a length of exactly 8.  [/Users/Mohamad/.rvm/gems/ruby-2.0.0-p247/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:344]:
Did not expect errors to include "is the wrong length (should be 8 characters)" when post_code is set to "xxxxxxxx", got error: is the wrong length (should be 8 characters)

  2) Error:
AddressTest#test_: Address should only allow integers for post_code. :
NoMethodError: undefined method `gsub' for 0.1:Float
    app/models/address.rb:12:in `sanitize_post_code'

154 runs, 198 assertions, 1 failures, 1 errors, 0 skips
```

Here are the tests:

``` ruby
  should ensure_length_of(:post_code).is_equal_to(8)

  test 'post_code is sanitized before validation' do
    address = build(:shipping_address, post_code: "12345-678")
    address.save
    assert_equal "12345678", address.post_code
  end
```

The model:

``` ruby
class Address < ActiveRecord::Base
  belongs_to :addressable, polymorphic: true
  # ...
  validates :post_code, numericality: { only_integer: true }, length: { is: 8 }
  before_validation :sanitize_post_code

private

  def sanitize_post_code
    self.post_code = post_code.gsub(/\D/, '') if post_code.present?
  end
end

```

And the migration.

``` ruby
class CreateAddresses < ActiveRecord::Migration
  def change
    create_table :addresses do |t|
      t.references :addressable, polymorphic: true, null: false
      t.string :type, null: false

      # ..
      t.string :post_code, null: false
    end
  end
end
```

Any clue why the failures are happening?

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
