### ISSUE TITLE
Associations foreign key issue with namespaced models

### ISSUE THREAD

**Issue by gdlx** [thoughtbot/shoulda-matchers#589]
I can't make `have_many`/`belong_to` work with namespaced models associations.

I'm using model classes like `Company::Project::Group` `has_many` `Company::Project::Members`

When testing this:

``` ruby
  it do
    should have_many(:members).class_name('Company::Project::Member')
  end
```

I get this (as expected):

```
Failure/Error: should have_many(:members).class_name('Company::Project::Member')
  Expected Company::Project::Group to have a has_many association called members (Company::Project::Member does not have a group_id foreign key.)
```

I change my test to this:

``` ruby
  it do
    should have_many(:members).
      class_name('Company::Project::Member').
      with_foreign_key('company_project_group_id')
  end
```

The `company_project_group_id` field exists, but I still get this error:

```
Failure/Error: should have_many(:members).class_name('Company::Project::Member').with_foreign_key('company_project_group_id')
  Expected Company::Project::Group to have a has_many association called members()
```

As you can see, there's no error detail so I don't know why the test is failing...
I get the same behavior testing the inverse `belongs_to` relation:

```
Failure/Error: should belong_to(:group).class_name('Company::Project::Group').with_foreign_key('company_project_group_id')
  Expected Company::Project::Members to have a belongs_to association called group ()
```

Using rails-4.1.6, active-record 4.1.6 w/ MySQL,  rspec-rails-3.1.0, shoulda-matchers 2.7.0

Nothing special in my models associations:

``` ruby
class Company::Project::Group < ActiveRecord::Base
  has_many :members,
    class_name: 'Company::Project::Member',
    inverse_of: :group
[...]

class Company::Project::Member < ActiveRecord::Base
  belongs_to :group,
    class_name: 'Company::Project::Group',
    inverse_of: :members
[...]
```

Am I doing something wrong ?

**Comment by DiegoOrejuela** [comment]
@mcmire Hi. I am a bit confused about this. I think the expected behavior is that it identifies the foreign key that the relationship should have based on where the class is located. In the case of `Company::Project::Group` the default foreign key is `company_project_group_id` . So I think it could be something that could be improved.

**Comment by mcmire** [comment]
@DiegoOrejuela It sounds like the OP was able to solve his problem, so that's why I closed this particular issue, but it's possible there is still a bug here — I would need more information to know for sure. So if you are getting this error I think what would be most helpful is a complete example of the association in your model and the tests you have in your test file. Preferably also in a new issue :)
