### ISSUE TITLE
delegate_method not supporting assignment methods

### ISSUE THREAD

**Issue by BenMorganIO** [thoughtbot/shoulda-matchers#606]
Currently in a project I am doing something like this:

```ruby
class Product < ActiveRecord::Base
  has_one :price

  delegate :amount, :amount=, to: :price
end
```

You can make an inference of how the price model might work, but lets look at how we would test our product model.

```ruby
require 'rails_helper'

describe Product do
  it { should have_one :price }

  it { should delegate_method(:amount).to :price }
  it { should delegate_method(:amount=).to :price }
end
```

The output is as so:

```shell
$ zeus rspec spec/models/product_spec.rb
..F

Failures:

  1) Product should delegate #amount= to #price object
     Failure/Error: it { should delegate_method(:amount=).to :price }
     ArgumentError:
       wrong number of arguments (0 for 1)
     # ./app/models/product.rb:4:in `amount='
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/independent/delegate_method_matcher.rb:268:in `public_send'
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/independent/delegate_method_matcher.rb:268:in `block in subject_delegates_to_target_correctly?'
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/doublespeak/world.rb:12:in `with_doubles_activated'
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/independent/delegate_method_matcher.rb:267:in `subject_delegates_to_target_correctly?'
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/independent/delegate_method_matcher.rb:136:in `matches?'
     # ./spec/models/product_spec.rb:7:in `block (2 levels) in <top (required)>'
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/zeus-0.15.1/lib/zeus/rails.rb:202:in `test'
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/zeus-0.15.1/lib/zeus.rb:148:in `block in command'
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/zeus-0.15.1/lib/zeus.rb:135:in `fork'
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/zeus-0.15.1/lib/zeus.rb:135:in `command'
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/zeus-0.15.1/lib/zeus.rb:50:in `go'
     # -e:1:in `<main>'

Finished in 0.3338 seconds (files took 1 minute 2.8 seconds to load)
6 examples, 1 failure

Failed examples:

rspec ./spec/models/spree/product_spec.rb:9 # Product should delegate #amount= to #price object
```

Hope this helps :)

**Comment by mcmire** [comment]
I would take a PR that added this API:

```
it { should delegate_method(:amount=).to(:price).with_arity(1) }
```

**Comment by christianrolle** [comment]
Before the DelegateMethodMatcher API is enhanced with DelegateMethodMatcher#with_arity, I'd like to discuss, if the feature is actually reasonable. Do we really need to test the delegation targets method arity? In my opinion the class under testing concern should only test, if the method is delegated to the right target. The expected arity should have been tested there already.
There is no doubt that testing message delegation, which expects more than 1 parameter should work, but maybe just by bug fixing instead of enhancing the API?

**Comment by mcmire** [comment]
@christianrolle So you're saying just test that `amount=` is called at all, regardless of how many arguments it was given?

So here's a question: if you were to write this test in RSpec, what would you say? Would you say this:

``` ruby
price = double(:price, amount=: nil)
allow(subject).to receive(:price).and_return(price)

subject.amount = 1.23

expect(price).to receive(:amount=)
```

or would you say this (`with` added to the expectation):

``` ruby
price = double(:price, amount=: nil)
allow(subject).to receive(:price).and_return(price)

subject.amount = 1.23

expect(price).to receive(:amount=).with(1.23)
```

I would probably use the latter form, because I want to check that 1.23 is being sent to `amount=`.

But this is exactly what `with_arguments` does -- it lets you pass arbitrary arguments to the delegate method and assert that those arguments were passed along.

So taking another look at this issue, I don't think that `with_arity` is necessary, either. What do you think?

**Comment by christianrolle** [comment]
I'm not sure, if testing `with_arguments` is even necessary.
In my opinion message delegation is not about the method definition, but that the message is delegated to a certain object. 
That object should have its receiver tested (including its parameter expectation). 
Otherwise we double test the parameter expectation: in the delegating object and in the target object.
Or am I missing a point? Is my perspective weird?

**Comment by mcmire** [comment]
If you never tested that the delegating method passed the arguments correctly on to the delegate method, then this method would pass such a test:

``` ruby
def amount=(*whatever)
  price.amount = nil
end
```

It's like if you had two people -- a navigator and a pilot -- and the job of the navigator was to take instructions from the ground and pass on those instructions to the pilot. Well, if the navigator tells the pilot to *go*, but doesn't tell her *where* to go, is the navigator doing a good job?

**Comment by christianrolle** [comment]
At first I have to point out that this specific issue request made me think more about the sense of testing arguments for delegating methods.
You are right. the method:
```ruby
def amount=(*whatever)
  price.amount = nil
end
```
will pass such a test. But is that method really delegating?
I also want the navigator (in navigator/pilot example) to tell the pilot *where* (target object) to go. I just think it's probably worthless telling the pilot *how* (which arguments) to go there, because she should know how to fly.
```ruby
def amount=(*whatever)
  price.amount = nil
end
```
... does NOT delegate. It behaves different.
Could it be, that testing the arguments means suspecting the implementation not to delegate?
But then we also had to test the result, shouldn't we?

But I also see a gap in my thoughts. How can the spec of `amount=` reveal that there should be pure delegation? Maybe an answer is using a delegation matcher which declares delegation?

**Comment by mcmire** [comment]
Yeah, my point is that it would be possible to write a method that would pass the test even though its intent no longer matches the intent of the test itself. The behaviors *are* different -- that's exactly the point -- but the test would still pass regardless.

(Side note: Personally, I don't find these delegation matchers to be that useful, because if your delegation methods aren't working probably then you're probably not using them correctly. The matchers don't do a whole lot in my opinion to ensure that (and you probably have a higher-level test to cover this anyway). But, the matchers exist and we have them, so we should make sure they can be used well.)

**Comment by mcmire** [comment]
Also, I'm going to close this since #718 is open, so we don't need this lying around anymore. (I guess I'll have to figure out what to do with that PR, though.)
