### ISSUE TITLE
validates_inclusion_of fails when calling `.count` on ActiveRecords

### ISSUE THREAD

**Issue by andycandrea** [thoughtbot/shoulda-matchers#628]
For example, the following:

```
it { should validate_inclusion_of(:some_integer_column).in_range(0..described_class.count) }
```

fails with the following error:

```
Did not expect errors to include "is not included in the list" when some_integer_column is set to 1, got error: is not included in the list
```

When the validation is triggered, there are no instances of the `described_class`, so `1` is not in the accepted range and shouldn't be used as a test value (except for testing that the validation doesn't allow incorrect values). I tried this on both version `2.6.2` with `ensure_inclusion_of` and version `2.7.0` with `validates_inclusion_of` and got the same result each time. I also tried changing my range from `0..0` with version `2.7.0`, which did work as intended.

Thanks, and let me know if I can provide any more info.

**Comment by mcmire** [comment]
@andycandrea Can you write a failing test case for this?

**Comment by andycandrea** [comment]
@mcmire Sorry for the delay--I'll definitely do so when I get a chance. A little more info in the mean time: I haven't touched this particular bit of code in a while, but, if I recall, it may have turned out to be more of an issue of Rails not liking inclusion validations that include `Model.count` than an issue of shoulda-matchers. It's probably worth keeping this open until I can do a little more investigating to be sure, though.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
