### ISSUE TITLE
How to test validate_uniqueness_of with if conditions

### ISSUE THREAD

**Issue by untidy-hair** [thoughtbot/shoulda-matchers#640]
Hi, I know shoulda-matcher doesn't support if condition and how we should test those cases with `validate_presence_of` through #180.
But the same way does not work for `validate_uniqueness_of`

``` ruby
# user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :name, if: :active?
end
```

``` ruby
#schema
  create_table "users", force: :cascade do |t|
    t.string   "name"
    t.boolean  "active"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
```

``` ruby
# spec/user_spec.rb
describe User do
  context 'conditional-validation 1' do
    before { allow(subject).to receive(:active) { true } }
    it { should validate_uniqueness_of(:name) }
  end

  context 'conditional-validation 2' do
    before { subject.active = true }
    it { should validate_uniqueness_of(:name) }
  end
end
```

This is because we cannot specify active=true for the second object we create for testing. If you change line 242 in lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb like so, it works.

``` ruby
 242:         @subject = subject.class.new(active: true)
```

Is there any good way to test this kind of stuff with shoulda?
Thanks!

**Comment by mcmire** [comment]
Yeah, this one's a tricky one, because the uniqueness matcher operates on a new instance of the model, against an existing instance. The subject is considered the existing instance, so any changes to it won't actually be carried through. I agree that this should be possible, although I don't have any immediate thoughts about this.

**Comment by untidy-hair** [comment]
@mcmire, thank you! If I come up with a good idea, I will post it, too.

**Comment by dhumphreys** [comment]
@mcmire @untidy-hair I have ran into this issue as well. Wouldn't simply duplicating the subject on line 242 solve the problem?

```@subject = subject.dup```

**Comment by denispeplin** [comment]
I'm trying to test unique scoped attributes conditionaly:

```ruby
validates :name, :code, uniqueness: { scope: :client_id }, if: :is_active?
```

```
Failure/Error: expect(subject).to validate_uniqueness_of(:name).scoped_to(:client_id)
       Expected errors to include "already exists" when name is set to "Receiver 2",
       got no errors
```

**Comment by mcmire** [comment]
@denispeplin Your workaround is really just saying the same thing, isn't it? Do you actually want saving the subject to raise an error?

**Comment by denispeplin** [comment]
@mcmire, I believe I'm actually saving a duplicate inside the block and then testing for the error using the `raise_error` matcher. Am I wrong?

**Comment by mcmire** [comment]
@denispeplin Oh, I see what you're doing. Yup, that makes sense.

**Comment by glentregoning** [comment]
@untidy-hair I realize this isn't a fix but another work around here you could use in the short term is to stub your is_active method on all instances in your test scope? 



```
# spec/user_spec.rb
describe User do
  context 'conditional-validation 1' do
    before do
       allow_any_instance_of(User).to receive(:is_active?).and_return(true)
    end
    it { should validate_uniqueness_of(:name) }
  end

  context 'conditional-validation 2' do
    before { subject.active = true }
    it { should validate_uniqueness_of(:name) }
  end
end

```

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
