### ISSUE TITLE
"validate_absence_of" throws ActiveRecord::SerializationTypeMismatch if attribute is serialized to an array

### ISSUE THREAD

**Issue by montague** [thoughtbot/shoulda-matchers#643]
``` ruby
class Pizza < ActiveRecord::Base
  serialize :toppings, Array
  validates :toppings, absence: true
end

# shoulda assertion
should validate_absence_of(:toppings)
```

Running this code in `activerecord 4.2.0` results in the following error:

```
ActiveRecord::SerializationTypeMismatch: Attribute was supposed to be a Array, but was a String. -- "an arbitrary value"
```

I think the issue stems from https://github.com/thoughtbot/shoulda-matchers/blob/eadbdf8ee9af23945b0931e86c0cdd96fee97cae/lib/shoulda/matchers/active_model/validate_absence_of_matcher.rb#L77, where the value cannot be correctly inferred from the column type.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
