### ISSUE TITLE
validates_numericality_of with symbol instead of number.

### ISSUE THREAD

**Issue by esbanarango** [thoughtbot/shoulda-matchers#688]
Hello and thank you for this project.

I have this validation on my model:

``` ruby

    validates_numericality_of :quantity_min, greater_than: 0
    validates_numericality_of :quantity_max, greater_than: :quantity_min
```

it works as expected but when I try to test it with the _shoulda-matchers_ validators:

``` ruby

it { is_expected.to validate_numericality_of(:quantity_max).is_greater_than(:quantity_min)}

```

I got: `undefined method '+' for :quantity_min:Symbol`

**Comment by mcmire** [comment]
Thanks for the report. We don't support method names for those options, but we'd gladly take a pull request that fixes this.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
