### ISSUE TITLE
`allow_value` matcher throws error when is used without the `for`

### ISSUE THREAD

**Issue by maurogeorge** [thoughtbot/shoulda-matchers#706]
Using the `allow_value` matcher on 2.7.0/2.8.0 displays the following error:

```
Failure/Error: it { is_expected.to allow_value('jon@example.com', 'jon+1@example.com.br') }
     NoMethodError:
       undefined method `=' for #<ContactForm:0x007fc408bcbd48>
```

This occurs when the `for` method has not been passed to the `allow_value`, eg.

```
it { is_expected.to allow_value('jon@example.com', 'jon+1@example.com.br') }
```

**Comment by mcmire** [comment]
Yup, definitely a long standing but known issue. I'm working on refactoring the tests as a part of switching `allow_value` with `allow_values` for #692, and I'll make this change as a part of that.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
