### ISSUE TITLE
Shoulda matcher does not work with attr_reader

### ISSUE THREAD

**Issue by debajit** [thoughtbot/shoulda-matchers#764]
I would like to test a validation done on an attribute of the following class:

```
class R
  include ActiveModel::Validations

  attr_reader :attribute

  validates :attributes, presence: true

  def initialize(attribute = {})
    @attribute = attribute
  end
end
```

Now my test is like this:

```
RSpec.describe R, type: :model do
  context 'validations' do
    subject { R.new(1) }

    it { should validate_presence_of(:attribute) }
  end
end
```

But this results in an error:

```
NoMethodError:
   undefined method `attributes=' for
```

If I change the attr_reader to an attr_accessor, then the test passes.

How can I leave the attr_reader as it is, and still get the test with the Shoulda matcher to pass?

**Comment by mcmire** [comment]
Think about how you'd write a test for `validate_presence_of`. Wouldn't you try to do something like this?

``` ruby
r = R.new(1)
r.attribute = nil
expect(r.errors[:attribute]).to include("can't be blank")
```

If `attribute` can't be set, then why put a validation on it?

**Comment by mcmire** [comment]
I'm closing this issue since there hasn't been a response in a while but feel free to continue the discussion if need be.

**Comment by RyanNaughton** [comment]
I think this issue should be re-opened.

A presence check should not rely upon the ability to use a setter method. There are many legitimate cases where you don't want to expose a setter, but you still need to ensure that the attribute is present. 

My suggestion is that shoulda should stub the attribute getter method to return nil to check that the validation fails and stub it to return a non-nil value to ensure the validation passes.

Part of the reason is that in reality the attributes being checked don't even have to be simple getters. The presence check could be for a virtual attribute. Since the validation is really just calling that method, the best way to test it in my view is to stub the method.

**Comment by jererutter** [comment]
@mcmire I have classes that can only have attributes set through instantiation, which disallows me from using this gem without adding fake attr_accessor methods in my testing.

e.g.

```
Class Widget
  include ActiveModel::Validations

  validates_presence_of :fake_attribute

  def initialize(args = {})
    @fake_attribute = args[:fake_attribute]
  end
end
```

In the case of this class type, I know I'll always have the attributes I need when it comes time to instantiate this class, so it seems unnecessary to add setters.

**Comment by mcmire** [comment]
Alright, I'll reopen this issue.

**Comment by mcmire** [comment]
I'm going to close this issue as this gem is not designed to work with classes where there aren't writer methods, it's designed to operate against an already instantiated instance of a class instead of the class as a whole. We'd have to change _all_ of the matchers to support that use case and I don't have time to do that. I would suggest writing your own matchers to do this. Sorry.
