### ISSUE TITLE
validate_inclusion_of allows values outside of array in validation

### ISSUE THREAD

**Issue by sfcgeorge** [thoughtbot/shoulda-matchers#769]
In model:

``` ruby
validates :section, inclusion: { in: [0, 1, 2] }
```

Correct desired test:

``` ruby
should validate_inclusion_of(:section).in_array([0, 1, 2])
```

That much is fine. But if the array used in the test is changed to `[0, 1]` it still passes! However if using `in_range` then it works as expected.

Test variations:

``` ruby
should validate_inclusion_of(:section).in_array([0, 1, 2])    # Passes: correct
should validate_inclusion_of(:section).in_array([0, 1])       # Passes: wrong !!!
should validate_inclusion_of(:section).in_array([0, 1, 2, 3]) # Fails: correct

should validate_inclusion_of(:section).in_range(0..2) # Passes: correct
should validate_inclusion_of(:section).in_range(0..1) # Fails: correct
should validate_inclusion_of(:section).in_range(0..3) # Fails: correct
```

**Comment by alejandrogutierrez** [comment]
I think It is working as expected.
```ruby
should validate_inclusion_of(:section).in_array([0, 1]) 
```

This passes because all array elements are valid for your validation.

**Comment by sfcgeorge** [comment]
But now my validation is inadvertently allowing in junk values. The point of adding the test is to make sure I haven't made a mistake in the validation and it does exactly what it's supposed to isn't it?

**Comment by alejandrogutierrez** [comment]
```ruby
should validate_inclusion_of(:section).in_array([0, 1]) 
```

This make sure that your validation accepts either 1 or 2 values for your section attribute what it is ok.
I don't know why your validation is inadvertently allowing junk values. What do you mean?

**Comment by sfcgeorge** [comment]
`section` field is an integer and should only ever be allowed to contain the values `1`, `2` or `3`. But lets say I decide later to change section to only allow `0` or `1`—I update my test to `in_array([0, 1])` and forget to change my validation; but the test still passes!

Am I totally misunderstanding what `in_array` is for? Those are the only values I want to be valid, no more, no less.

**Comment by alejandrogutierrez** [comment]
Yes, your test is passing because 1 and 2 are still valid. I think there is not an assert that compare the array in test and the array in validation are the same.

Maybe if values that you allow are continuos (range) you can use `in_range`. Be careful using `in_range` cause it validates that minimum and maximum values are valid and minimum - 1 and maximum + 1 are invalid. It does not test all range values.

**Comment by sfcgeorge** [comment]
Hmm I see why it does this and I'd understand if you decided it's expected behaviour. It just feels like a bug if your test can be different from your validation yet everything still passes.

I guess apps usually grow in size rather than shrink so the case of removing an item from an array validation is uncommon. But it could happen if refactoring into smaller models, for example.

I previously was checking upper bound, lower bound, upper invalid and lower invalid as you said—so `in_range` is perfect. Shoulda is making my tests much shorter, it's great. Thanks :)

**Comment by turboladen** [comment]
I kinda agree with @sfcgeorge --the matcher seems misleading if the test still passes despite the array you specify in the test doesn't match what's in your code. I understand the procedure behind the matcher (checking inclusion), but that just doesn't seem right. The matcher implies to me that it checks that the arrays are equal, not just that the `in_array` values are in the model's `inclusion:` array.

Just thought you might want the feedback. Maybe updating the docs to make this clearer could dispell some of this? Looking at https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb#L23.

**Comment by mcmire** [comment]
Okay, that's a fair point.

I'll reopen this issue to remind myself to fix this.

**Comment by turboladen** [comment]
:+1:

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
