### ISSUE TITLE
Testing #has_many with multiple #order

### ISSUE THREAD

**Issue by jfragoulis** [thoughtbot/shoulda-matchers#774]
I have the following association:

``` ruby
class MyClass < ActiveRecord::Base
  has_many :my_assoc, -> {
    order("coalesce(my_assoc.order, 256) asc, my_assoc.updated_at asc")
  }
end

# spec 
it { expect(instance_of_myclass).to have_many(:my_assoc).order('coalesce(my_assoc.order, 256) asc, my_assoc.updated_at asc') }
```

I broke the order clauses into one for each column and consequently I also updated the spec into what I would expect to be the right way: 

``` ruby
class MyClass < ActiveRecord::Base
  has_many :my_assoc, -> {
    order("coalesce(sku_images.order, 256) asc").order(updated_at: :asc)
  }
end

# spec 
it { expect(instance_of_myclass).to have_many(:my_assoc).order('coalesce(my_assoc.order, 256) asc').order(updated_at: :asc) }
```

The above fails with the following message:

```
Failure/Error: it { expect(instance_of_myclass).to have_many(:my_assoc).order('coalesce(my_assoc.order, 256) asc').order(updated_at: :asc) }
       Expected MyClass to have a has_many association called my_assoc (my_assoc should be ordered by coalesce(my_assoc.order, 256) ascmy_assoc should be ordered by {:updated_at=>:asc})
```

**Comment by mcmire** [comment]
@jfragoulis This is one of those cases where I would honestly write a "real" test for this. That said, I suppose you're right that this should work. Actually, I just took another look at the association matchers and it appears that none of them support using a qualifier more than once, anyway -- if you repeat a qualifier, it `or`s the qualifiers together instead of overriding the previous usage of the qualifier. However of course `order` (and `conditions`) for that matter shouldn't override any previous usage or `or` usages together, it should `and` them together.

Anyway, thanks for submitting this issue. I don't know when I will get to it, but it is noted.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
