### ISSUE TITLE
Uniqueness matcher doesn't work when using `strict` on other attributes

### ISSUE THREAD

**Issue by dwilkie** [thoughtbot/shoulda-matchers#778]
E.g.

``` ruby
class Account < ActiveRecord::Base
  validates :email :uniqueness => true
  validates :uuid, :presence => true, :uniqueness => true, :strict => true
```

``` ruby
describe Account do
    subject { create(:account) }
    it { is_expected.to validate_uniqueness_of(:email) }
end
```

The following fails because inside shoulda matchers `subject.class.new` is called. In this case `uuid` will be blank and the strict validation causes an error to be raised.

**Comment by mcmire** [comment]
Ah... this is interesting. This is generally not a problem without the use of `strict` because even if the `subject` is invalid all we care about is whether `email` is valid. With `strict` in place, `subject` must be valid.

I guess a naive solution to this would be to find an existing Account, duplicate it, and then attempt to validate it using the same value for email (asserting that it raises a validation exception) and then using a different value for email (asserting that it does not raise the exception). I'm not sure how duplicating the existing record will affect existing behavior, though -- I'd have to take a closer look at that.

In any case... I guess there isn't a good way to get around this problem. Sorry about that. You might have to write the test by hand in this case.

**Comment by dwilkie** [comment]
Yeh I haven't tried yet, but if replacing `subject.class.new` with `subject.clone` on line https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb#L258 solves the problem, and doesn't cause any tests to fail maybe that's the way to go

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
