### ISSUE TITLE
When having named root routes redirect_to does not work

### ISSUE THREAD

**Issue by AlexVPopov** [thoughtbot/shoulda-matchers#780]
I have different root paths for logged in and not logged in users:
```ruby
devise_scope :user do
  authenticated(:user) { root 'expenses#index', as: :authenticated_root }

  unauthenticated { root 'devise/sessions#new', as: :unauthenticated_root }
end
```

Since I added these routes, the following test started failing:
```ruby
it { should redirect_to action: :index }
```
with:
```bash
Failure/Error: should redirect_to action: :index
       Expected response to be a redirect to <http://test.host/> but was a redirect to <http://test.host/expenses>.
       Expected "http://test.host/" to be === "http://test.host/expenses".
```
Why does it expect `http://test.host/` and not `http://test.host/expenses`?

P.S. I also have a problem with this test:
```ruby
it { should route(:get, '/expenses').to(action: :index) }
```
which fails with:
```bash
 Failure/Error: it { should route(:get, '/expenses').to(action: :index) }
       The generated path </> did not match </expenses>.
       Expected: "/expenses"
         Actual: "/"
```
So again - why does the method `route` lead to '/'?

**Comment by mcmire** [comment]
So first a little context here: the `route` matcher is actually a combination of `assert_generates` and `assert_recognizes`, which come included in Rails. `assert_generates` takes a method and path and asserts that the routing layer knows how to determine the correct controller and action. `assert_recognizes` goes the other way and asserts that the routing layer knows which method and path is associated with a given controller and action.

Hence, when you write something like

``` ruby
it { should route(:get, '/expenses').to(action: :index) }
```

you're saying this:

* When a request is made to `GET /expenses`, Rails should route the request to ExpensesController#index
* The route associated with ExpensesController#index is `GET /expenses`

But the last statement isn't true, because the route for ExpensesController#index is `GET /`. It might not be the *only* route, but it's the first route that the routing layer sees, and that's the one that matters.

So what can you do about this? I would first try removing the ambiguity here by modifying your routes so that you don't have two routes that are associated with the same controller/action. If that's not a viable option, you could also use `route_to` from rspec-rails, which is a wrapper around only `assert_recognizes` (remember, that's the one that goes from method/path to controller/action). So you could say:

``` ruby
it "routes GET /expenses to #index" do
  expect(get: "/expenses").to route_to("expenses#index")
end
```

---

I think in the case of `redirect_to(action: :index)` it's the same way. Internally, `action: :index` (or really `controller: :expenses, action: :index` is converted to a path, which is compared with the redirect-to path that your action responds with. Well, the expected path in this case is the first route that matches `expenses#index`, so like the above, this will resolve to the root path.

So you may have to be explicit here:

``` ruby
it { should redirect_to(expenses_path) }
# or, if you like:
it { should redirect_to("/expenses") }
```

Hope this helps.

**Comment by AlexVPopov** [comment]
Wow, thank you a lot Elliot, thank you for taking the time and explaining
that to me. I was suspecting it was something like that, but couldn't
understand the exact mechanism, which you described so well. You also
provided solutios, which is also very kind of you.
:)

**Comment by mcmire** [comment]
Awesome, glad I could help!
