### ISSUE TITLE
Add `have_foreign_key` spec

### ISSUE THREAD

**Issue by BenMorganIO** [thoughtbot/shoulda-matchers#808]
While doing my specs, there's not much for me to make sure that I did my foreign keys up right. I absolutely love shoulda for its ability to make sure I didn't make a typo when setting up a relationship or a join table.

While creating foreign keys such as:

``` ruby
t.foreign_key :spree_products, on_delete: :cascade, column: :product_id
t.foreign_key :spree_taxons, on_delete: :cascade, column: :taxon_id
```

Now this is fun and amazing, except there's this call to `dependent(:destroy)` in the model. This shouldn't be there. Also, what if you end up using the old syntax while using Rails 4.2:

``` ruby
t.foreign_key :spree_products, dependent: :destroy, column: :product_id
t.foreign_key :spree_taxons, dependent: :destroy, column: :taxon_id
```

You might not catch this mistake until its too late...

I'm opening this PR to get thoughts on adding a should matcher for this. Would also want to add a matcher that basically calls `belongs_to` and `have_foreign_key` as well; for sugar's sake. Wanting to get my hands dirty in shoulda matcher source code.

**Comment by mcmire** [comment]
Hey @BenMorganIO I haven't forgotten you -- it's just that I've been a little preoccupied with some bugfixes lately.

We've talked about this before -- see #730. You can read the feedback there, but since we tend to create tools that we ourselves will use, I also shopped the idea around internally to see how what my teammates there thought. Here was some of the initial feedback I got:

* "that feels very deep database level-y"
* "I don't think app code should be testing something almost completely divorced from Rails... `has_many` at least is in the ActiveRecord sphere of influence"
* "If you remember to write the 'have_foreign_key' spec, what are the odds you forget to add the foreign key in the migration?"
* "Following the inside-out testing idea, I don't think I've run into a case where I've wanted feedback at that level, and I don't think those will actually catch any mistakes"

What that means is that if we did add a matcher like this, it's probably something we wouldn't use. I don't know what I feel about this -- I like supporting the community, but I also don't want to add something that we're not passionate about.

Now, this doesn't mean this isn't a good idea, but I think we're looking for something that's more tied into Rails. So instead of making a matcher that tests that the foreign key is there, what about a matcher that tests that when I destroy a record it destroys all associated records too? I can see that as something that's valuable. Plus, this test should work regardless of how the behavior is implemented.

**Comment by BenMorganIO** [comment]
I remember thinking the same line of thought as your colleagues with `have_db_index`. I used to agree with them, until I wrote this spec:

```ruby
shared_example 'acts_as_paranoid' do
  it { is_expected.to be_paranoid }
  it { is_expected.to have_db_column :deleted_at }
  it { is_expected.to have_db_index :deleted_at }
end
```

Since a _every_ query to the table is going to have `WHERE deleted_at IS NULL` then you're going to want that indexed. However, I wouldn't remember to add that all of the time. Since I added that to the shared example, I could just do:

```ruby
describe User do
  it_behaves_like 'acts_as_paranoid'
end
```

And then boom! You immediately get three specs saying:

- Did you make it paranoid?
- Did you add the column?
- __Did you add the index?__

I constantly forget to on the last one. This helps me remember to add it.

So, I do think we should have a `have_foreign_key`, but as an initial building block. We really should have it hooked up to the `belong_to`. Why: you forget to add that foreign key in half of the time; at least that's me.

What I really should be proposing is perhaps a config option:

```ruby
setup do |config|
  config.belongs_to_with_foreign_keys = true
  config.dependent_destroys_with_fk_on_delete_destroy = true
end
```

those are some long/descriptive configs, but I think you get the idea. The purpose of shoulda (to me at least) has always been to make sure you didn't make a spelling mistake when you create a new HABTM or something.

@mcmire WDYT about this?

**Comment by bsodmike** [comment]
+1 to @BenMorganIO for `it_behaves_like 'acts_as_paranoid`.  It would be nice to have the matcher for fk's in Shoulda too.

**Comment by BenMorganIO** [comment]
Yep agreed. Would be great for the `belong_to` matcher too.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
