### ISSUE TITLE
[question] How to test where.not conditions on associations?

### ISSUE THREAD

**Issue by abitdodgy** [thoughtbot/shoulda-matchers#810]
I looked through the source code, but I found nothing.

``` ruby
class User
  enum status: {
    active: 1,
    cancelled: 2
  }

  has_one :subscription, -> { where.not(status: stautses[:cancelled]) }
end
```

How do I test the condition on the `has_one :subscription` association?

``` ruby
should have_one(:profile).conditions(status: ... )
```

Easy enough to write a custom test, but I thought I'd check before reinventing the wheel.

Ideally, maybe something like...

``` ruby
should have_one(:profile).conditions.not(status: :foo)
```

**Comment by mcmire** [comment]
Yeah, there isn't a way to do that right now, so you'd have to write something custom.

I think really what we should do is deprecate `conditions` and `order` in favor of another qualifier. Then you could write something like:

``` ruby
should have_one(:profile).scoping_relation { where.not(status: 2) }
```

or perhaps even:

``` ruby
should have_one :profile, -> { where.not(status: 2) }
```

The way this would work is that it would evaluate the block in the context of the associated model and compare it to the Relation that your association has built, and if there are differences then it fails the test. I started working on this a while back but didn't finish it.

**Comment by abitdodgy** [comment]
@mcmire how difficult is it to do this, assuming I'm not familiar with the internals of shoulda?

**Comment by mcmire** [comment]
I don't think it'd be terribly difficult, but I guess that's because I have some idea of what I'd want to do here already. I'll try to explain it anyway...

Whenever you use an association matcher like `have_one`, it creates an instance of [Shoulda::Matchers::ActiveRecord::AssociationMatcher]. The logic for most of the qualifiers here actually live in separate *Matcher files, so you'd probably want to make one of those to represent this `scoping_relation` or `with_scoped_relation` or whatever-it-ends-up-being-called qualifier. Then what you'd have to do is combine the logic that the `order` and `conditions` qualifiers are doing. In those two cases, I'm using this [OptionVerifier] class to compare the given `order` or `conditions` with the respective `order` and `where` clauses of the relation of the association -- my point is that it's a little nuts, and I don't really like it anymore and so you may not want to use that. If you look for a [ModelReflector](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_record/association_matchers/model_reflector.rb#L40) class there's some code that accesses different pieces of a relation, and you may want to do a similar thing.

As far as writing tests goes, you can either open up `association_matcher_spec.rb` and take a look at some of the existing tests and go off of those, or there's this `define_model` helper that you can use and that will let you make a blank model and stick whatever you want in the class body.

Hopefully that was somewhat helpful...

[Shoulda::Matchers::ActiveRecord::AssociationMatcher]: https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_record/association_matcher.rb
[OptionVerifier]: https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_record/association_matchers/option_verifier.rb#L105
[ModelReflector]: https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_record/association_matchers/model_reflector.rb

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
