### ISSUE TITLE
Value not translated in validate_length_of_matcher

### ISSUE THREAD

**Issue by OfTheDelmer** [thoughtbot/shoulda-matchers#858]
The [translate_messages!](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_model/validate_length_of_matcher.rb#L301) method in `ValidateLengthOfMatcher` does not include the `value` in the options passed to  `default_error_message`. This showed up for me when I changed the I18n message to include the value and my tests could not generate a correct expected message.

`project/locale/en.yml`

``` yml
en:
  errors:
    messages:
      too_long: "with %{value} should be at most %{count} characters"

```

`spec/some_length_validation_spec.rb`

``` ruby
it { is_expected.to validate_length_of(:ticker_symbol).is_at_most(4) }
```

which fails with something like the following:

``` ruby
Failure/Error: it { is_expected.to validate_length_of(:ticker_symbol).is_at_most(4) }
   Expected errors to include "with  should be at most 4 characters" when ticker_symbol is set to "xxxxxxx",
   got errors:
    * "with xxxxxxx should be at most 4 characters" (attribute: ticker_symbol, value: "xxxxxxx")
```

---

**NOTE**: [active model](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/locale/en.yml) says the following in its `active_model/locale/en.yml`

> ```
> # The values :model, :attribute and :value are always available for interpolation
> ```

**Comment by mcmire** [comment]
Thanks for the report. Not sure when I can get to this, but I'll leave this open in the meantime.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
