### ISSUE TITLE
validate_confirmation_of does not work for integer columns

### ISSUE THREAD

**Issue by oniofchaos** [thoughtbot/shoulda-matchers#865]
When using the confirmation validation on an integer value, the `validate_confirmation_of` matcher does not work as it appears to use string values.

**Comment by mcmire** [comment]
Thanks for the report. I'm not sure when I'll get to this (a PR is encouraged), so I'll keep this open in the meantime.

**Comment by kheppenstall** [comment]
Confirmed this bug. No error with strings but had the following problem with integers:

Validation:
```ruby
validates_confirmation_of :unit_price_in_cents
```
Test:
```ruby
it { is_expected.to validate_confirmation_of(:unit_price_in_cents) }
```

Error:
<img width="719" alt="screen shot 2017-04-06 at 11 40 50 am" src="https://cloud.githubusercontent.com/assets/16868275/24767929/13e62948-1abe-11e7-9a37-03077191732f.png">

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
