### ISSUE TITLE
RSpec compound matchers

### ISSUE THREAD

**Issue by Szeliga** [thoughtbot/shoulda-matchers#882]
Hello,

I was playing around with compound matchers in RSpec (https://relishapp.com/rspec/rspec-expectations/v/3-4/docs/compound-expectations) and noticed that shoulda-matchers don't support them:

``` ruby
it { is_expected.to validate_presence_of(:firstname) & validate_presence_of(:lastname) }
```

results in

```
     NoMethodError:
       undefined method `&' for #<Shoulda::Matchers::ActiveModel::ValidatePresenceOfMatcher:0x007fa9c0bc2b60>
```

I was wondering about implementing this feature and creating a PR, is it something you would like to have in shoulda-matchers?

Best regards,
Szymon

**Comment by mcmire** [comment]
Someone else made a request for this a while back: #645.

Personally, I don't know if I'd use this. I feel like this would lead to long lines, and we like to keep lines under 80 characters.

That said, I am open to adding this if it makes writing tests easier or improves error messages. Is there a reason why you'd want to do this specifically?

**Comment by johncarney** [comment]
I've just run into the same thing. I'm refactoring some legacy shared examples and the specific thing I was hoping to do was this:

```ruby
shared_example_for "has attribute format validation" do |*attributes|
  RSpec::Matchers.define_negated_matcher :not_allow_values, :allow_values

  attributes.each do |attribute|
    it "validates the format of #{attribute.inspect}" do
      is_expected
        .to      allow_values("a valid value", "another valid value").for(attribute)
        .and not_allow_values("an invalid value", "this one's right out").for(attribute)
    end
  end
end
```

Now generally I prefer to stick to one assertion per example, but for something like format validation testing only allowed values doesn't make sense, nor does testing only disallowed values. So you either write two examples, which is needlessly inefficient, or build a custom matcher, which may be a little over the top.

More generally, it happens reasonably often that I want to test interdependent properties of an object that don't need to be tested in isolation. The ability to compose matchers is a lightweight way to build such complex assertions from simpler matchers.

**Comment by mcmire** [comment]
@johncarney

Sorry for the late reply on this, I was out.

That's an interesting use case. I don't completely disagree with you, but two thoughts: 1) If you get an error message from something like that, what does it look like? Is it helpful? 2) Couldn't you just as easily break up those two assertions into two lines? Or would you really prefer the second assertion to continue running if the first one fails?

**Comment by johncarney** [comment]
Thanks for getting back to me @mcmire. I've since discovered RSpec`s `aggregate_failures` feature, which let's me do what I want, so the answer to question 2 is yes I can if I aggregate failures, and yes I do want the second assertion to continue even if the first fails. For question one, aggregating failures gives separate error messages for each failed assertion.

I still think the ability to compose matchers is useful, but my requirement is less acute now :)

**Comment by mcmire** [comment]
@johncarney Cool.

@Szeliga Sorry, I just realized I never responded to your original post. I am trying to keep an open mind about this stuff -- I understand why you'd want that. At the same time, I can imagine it getting potentially hairy. What happens if you have five attributes and you want to ensure they're tested for presence? Do you end up writing this...?

``` ruby
it do
  is_expected
    .to validate_presence_of(:first)
    .and validate_presence_of(:second)
    .and validate_presence_of(:third)
    .and validate_presence_of(:fourth)
    .and validate_presence_of(:fifth)
end
```

That feels ugly to *me*, although I know that beauty is in the eye of the beholder, so that doesn't bother me too much.

Aside from the code aesthetics, though, the main reason that I've been a little opposed to this is that I don't think it makes sense to make it possible to use *every* matcher compoundly (is that a word?). Not only would it mean that we have to write tests to ensure that every matcher works that way -- which would be a LOT of work -- but also, I'm not sure that every matcher is amenable to being used that way. Lots of matchers support many options and can be used many different ways, and I feel like opening them up to being used in a compound way could open a can of worms. I don't know. It could be that I'm just being paranoid about this whole thing.

On the other hand, I know why you (and other people) have made this suggestion. I'm guessing it's because it feels weird to say this in the model...

``` ruby
validates :this, :and, :that, presence: true
```

...and yet say this in your spec:

``` ruby
it { should validate_presence_of(:this) }
it { should validate_presence_of(:and) }
it { should validate_presence_of(:that) }
```

I suppose if we had some kind of `validates` matcher that used `validate_presence_of`, `validate_format_of`, etc. internally, then that might make it better. So in theory you could say:

``` ruby
it { should validate(:this, :and, :that, presence: true) }
```

However, there are some design issues we'd run into here. What if you (as the user) are using a custom validator class, such as the [email_validator gem](https://github.com/balexand/email_validator)? You might could think that you'd be able to use it in shoulda-matchers too:

``` ruby
validates :email, email: true

it { should validate(:email, email: true) }
```

But then how would the gem how to validate an email address?

Anyway. You can kind of see why I haven't made a decision on all of this yet..

**Comment by johncarney** [comment]
I don't think I would generally want to test validation on multiple attributes at once. I agree that not every validation matcher would be amenable to compounding this way - in much the same way as some matchers don't negate well, some won't compound well. I was thinking specifically about things like `allows_value` which isn't on it's own a great assertion because the values that a validation does not allow are just as important as the ones it does. Perhaps you could try making `allows_value` compound-able and see where that takes you?

**Comment by mcmire** [comment]
Okay, sure. You've convinced me about `allow_value`, at least. I would gladly take a PR that would make it compound.

**Comment by johncarney** [comment]
Sweet. I'll give it a go, but may take me a couple of weeks to get started - currently busy packing for a 3-month stint overseas :)

**Comment by mcmire** [comment]
Oh, awesome, sounds like fun! No worries.

**Comment by myronmarston** [comment]
FWIW, if you want to support this, you merely need to include `RSpec::Matchers::Composable` in your custom matcher classes:

https://github.com/rspec/rspec-expectations/blob/master/lib/rspec/matchers/composable.rb

**Comment by mcmire** [comment]
Just ran into a case in which this would be useful: custom validators.

For example, if you have a custom email validator, and you want to use that validator in multiple models, and you have multiple tests to test that validation, you *could* extract those tests to a shared example. *Or*, you could make a method that combines all those tests:

``` ruby
def validate_as_email(attribute)
  allow_value("johnsmith@gmail.com").and.
    disallow_value("johnsmith").and.
    disallow_value("johnsmith@").and.
    ...
end
```

Of course, this would mean that we'd have to have a `disallow_value` matcher too. (There's already a DisallowValueMatcher so we can simply expose that.)

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!

**Comment by jasonkarns** [comment]
Just came across this when I discovered that I can't use the `.or` compound matcher.

My scenario is a polymorphic association. The model `has_one :agent` or `has_one :manager` (with :through, :source, and :source_type). Since the has_one associations are through a polymorphic association, only _one_ of the two will be populated (which one depends on the value of the `entity_type`).

I was hoping to do `it { should have_one(:agent).or have_one(:manager) }`

**Comment by mcmire** [comment]
@jasonkarns My suspicion is that testing such a case would not be as easy as using `.or`, but it's entirely possible I'm wrong. Typically changes to this gem have been extracted from real-world use cases, so if you can write a series of tests for this (not using `have_one`, just manually) and share what you came up with, then that would help in trying to figure out how we could use `.or` to accomplish this (or maybe extend the behavior of `have_one`, if that ends up being easier).
