### ISSUE TITLE
Question: How do the validation matchers actually work?

### ISSUE THREAD

**Issue by dogweather** [thoughtbot/shoulda-matchers#894]
I'm asking because in my own tests, I literally instantiate a new ActiveRecord model with the attribute in question set to `nil`. And then I test if it's `valid?`. I feel like this is the most robust way to test validations. How does shoulda-matchers do it?

I tried tracing through the code to learn how `validate_presence_of` does its test, but I couldn't find the actual test itself. I.e., for this particular matcher, we're checking if blank/empty is not a valid value ... but where and how is that done?

**Comment by olliebennett** [comment]
Hey @dogweather - be careful if your approach is only checking the record is valid overall.

Rather than doing something like this:

```ruby
# Test 1
u = User.new(name: "Ollie", email: nil)
u.validate
expect(u).not_to be_valid # either RSpec
refute(u.valid?) # ... or MiniTest
```

you must ensure you check the specific attribute under test:

```ruby
# Test 2
u = User.new(name: "Ollie", email: nil)
u.validate
expect(u.errors[:email]).to be_empty # RSpec
assert(u.errors[:email].empty?) # MiniTest
```

To see why, suppose that after adding this test, a new required attribute is defined (and validated), but then the `email` validation is accidentally removed again. Test 1 will continue to pass, because the record overall is still invalid; the test is not actually testing what you think it is. Test 2 avoids this shortcoming.

In answer to your actual question, I also cannot identify the specific line on which the "magic happens", but I would imagine it's similar in operation to Test 2 above. Hope that helps!

**Comment by mcmire** [comment]
Yup, @olliebennett basically answered the question. The code itself is complicated, but the procedure is simple:

1. Receive an instance of the model
2. Set the attribute in question on that record to `nil`
3. Call `valid?`
4. If a custom validation message was specified on the matcher with `with_message`, then check for the presence of that message within the list of validation errors on the attribute in question; otherwise, just check for the presence of *any* validation error on that attribute. (If `strict` is used then we check for the existence of a validation *exception*.)

As far as the code goes, it's admittedly a little spread out. But every validation matcher uses [AllowValueMatcher](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_model/allow_value_matcher.rb) internally, and it performs steps 1 and 2 directly. Steps 3 and 4 are farmed out to a [Validator](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_model/validator.rb) class.
