### ISSUE TITLE
JoinTableMatcher false negatives on symbol vs string join_table_name

### ISSUE THREAD

**Issue by ajvondrak** [thoughtbot/shoulda-matchers#907]
With an association on my model like

``` ruby
class Model < ActiveRecord::Base
  has_and_belongs_to_many :joins, join_table: :custom_name
end
```

the test

``` ruby
class ModelTest < ActiveSupport::TestCase
  should have_and_belong_to_many(:joins).join_table(:custom_name)
end
```

fails with a message that the join table "doesn't exist", which is checked by this line: https://github.com/thoughtbot/shoulda-matchers/blob/26a35978f635c2068ada2ab9d7f21fd228a205b4/lib/shoulda/matchers/active_record/association_matchers/join_table_matcher.rb#L27

The table actually does exist, but setting up breakpoints I noticed why this check failed. At least in my setup (maybe it depends on the DB adapter? I'm using mysql2), `connection.tables` returns an array of _strings_, but the above test provided the `join_table_name` as a _symbol_. Thus, `connection.tables.include?(join_table_name)` always winds up being `false` - a false negative.

If I change the test to instead say 

``` ruby
class ModelTest < ActiveSupport::TestCase
  should have_and_belong_to_many(:joins).join_table('custom_name')
end
```

then it passes.

It feels like the `JoinTableMatcher` should be agnostic to the string/symbol difference (since AR is when setting up the association).

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
