### ISSUE TITLE
Revisit spring 'incompatibility' issue

### ISSUE THREAD

**Issue by softwaregravy** [thoughtbot/shoulda-matchers#923]
Just coming back to this since I hit the same issue again recently. 

Spring issue: https://github.com/rails/spring/issues/209
Previous shoulda-matchers issue: https://github.com/thoughtbot/shoulda-matchers/issues/382

Spring is in the default Gemfile created by rails. The Getting Started section of your readme advises a way to set up shoulda-matchers which will cause errors when used with spring. Reading through the previous issues while working through this problem takes a while.

~~Did anyone ever get a solution that worked in both with spring and without spring? I can't seem to find a setup that works with both.  Was that the reason nothing was ever done?~~ I got it.

I would humbly suggest revisiting the decision not to fix this in shoulda in light of spring's increased prevalence or, alternatively, to update the docs so people can more easily find a solution.

If the latter, I'd be happy to propose a change to the docs. 

PS thanks for maintaining the gem

**Comment by mcmire** [comment]
Since that issue was posted, we made two changes to shoulda-matchers that were designed to help annihilate this bug.

First, the gem no longer auto-requires RSpec; it expects that to be present ahead of time. Second, and most importantly, it no longer automatically tries to mix all of its matchers into your test framework as soon as it's loaded; that will happen manually, at the request of the user, in `rails_helper.rb`. This is why the README mentions using a configuration block. By the time this block runs, RSpec should be fully available, regardless of whether `rails_helper.rb` was loaded *way* before tests are run (as when using Spring), or *just* before tests are run (as when not using Spring).

So if you're still getting errors when using Spring, that's very strange. I've not heard any complaints from any of my coworkers (at least the Spring-using ones) about this, but I'd be curious to know what kind of troubles you're having anyway so that we can address them.

**Comment by softwaregravy** [comment]
The commit I referenced on my personal project, I've actually reversed. After having other, unrelated trouble with spring, I stripped it out of my project and added back shoulda-matchers. Everything works fine without spring. 

I'll make a TODO for myself to try and recreate this issue. Realistically, I may never get to it.
