### ISSUE TITLE
Enum matcher should check for _prefix and _suffix

### ISSUE THREAD

**Issue by tejasbubane** [thoughtbot/shoulda-matchers#961]
`define_enum_for` matcher should also have an option to check for `_prefix` and `_suffix`. Something like this:

**conversation.rb**

``` ruby
class Conversation < ActiveRecord::Base
  enum status: [:active, :archived], _suffix: true
  enum comments_status: [:active, :inactive], _prefix: :comments
end
```

**conversation_spec.rb**

``` ruby
expect(Conversation).to define_enum_for(:status).with([:active, :archived])
                                                .and(_suffix: true)

expect(Conversation).to define_enum_for(:comments).with([:active, :inactive])
                                                  .and(_prefix: :comments)
```

**Comment by mcmire** [comment]
Wow. What did they do to that API?

Well... anyway... I think in order to test that option, I'll have to reimplement how `define_enum_for` works. ActiveRecord keeps track of which columns are enum columns by storing them in a class-level `defined_enums` hash. Each key is the column and each value is an array of possible values that the column takes. In this case, `_prefix` and `_suffix` change which methods get created, and that information is not stored in `defined_enums`. So what I may have to do here is change the matcher so that it checks which methods get created as well.
