### ISSUE TITLE
Validation numericality with condition raise an exception

### ISSUE THREAD

**Issue by Shoroh** [thoughtbot/shoulda-matchers#972]
Rails 5, minitest, model test:

```ruby
should validate_numericality_of(:items_sold).is_greater_than_or_equal_to(0).on(:update)
```
Message:

```bash
rails test test/models/product_test.rb
```
```log
/test/models/product_test.rb:13:in `<class:ProductTest>': undefined method `on' for
#<Shoulda::Matchers::ActiveModel::ValidateNumericalityOfMatcher:0x007f8973f258d8>
(NoMethodError)
```

model:
```ruby
validates :items_sold, numericality: { greater_than_or_equal_to: 0 }
```

P.S.
validate_presence_of works well!
```ruby
gem 'shoulda-context', '~> 1.2.1'
gem 'shoulda', '~> 3.5'
gem 'shoulda-matchers', '~> 2.0'

**Comment by mcmire** [comment]
@Shoroh This works in newer versions of shoulda-matchers, but unfortunately we haven't updated shoulda-context to be compatible with it yet. Sorry :( It's on our list, though.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
