### ISSUE TITLE
validates_associated matcher

### ISSUE THREAD

**Issue by ain** [thoughtbot/shoulda-matchers#983]
Would be nice to add [validates_associated](http://edgeguides.rubyonrails.org/active_record_validations.html#validates-associated) matcher as well so one could go with

```ruby
it { is_expected.to validate_associated(:associate) }
```

**Comment by mcmire** [comment]
Yup, this has been mentioned before (#133). Personally, I don't use this validation because it produces a validation error that I wouldn't ever want to show a user (a simple `validates_presence_of(:association)` works fine for me). But if you're interested in this then feel free to submit a PR.

I'm going to go ahead and close this PR so we don't leave this hanging out there.
