### ISSUE TITLE
validates_uniquness_of.scoped doesn't work with two foreign keys?

### ISSUE THREAD

**Issue by jemagee** [thoughtbot/shoulda-matchers#984]
Perhaps I am just trying to push the shoulda-matcher too far, but I've run into a problem.

A participant
```
belongs_to :game
belongs_to :team
```

A team must be unique within the confines of the team

`it {should validate_uniqueness_of(:team).scoped_to(:game)`

The model reflects
`validates :team, uniqueness: {scope: :game}`

The shoulda test fails with the following error

     ActiveRecord::InvalidForeignKey:
       PG::ForeignKeyViolation: ERROR:  insert or update on table "participants" violates foreign key constraint "fk_rails_990c37f108"
       DETAIL:  Key (team_id)=(0) is not present in table "teams".
       : UPDATE "participants" SET "team_id" = $1, "updated_at" = $2 WHERE "participants"."id" = $3

I'm relatively new to this but I have the feeling I'm just pushing the confines of the scope too much?

**Comment by mcmire** [comment]
Hey @jemagee. It looks like you're seeing this issue: https://github.com/thoughtbot/shoulda-matchers/issues/682#issuecomment-151715507. Some things have changed since then, so I'm curious as to why you are seeing this. You could try the suggestions mentioned in that issue and see if that fixes it for you. Just so I know, can you post a backtrace?

**Comment by jemagee** [comment]
I suppose I could try that, but the thing is, my issue is a bit more

I’m dealing with two foreign keys though, and to make things more complicated the team actually belongs to another model (division) that is required.

So if I’m reading this right, I’d have to use FactoryGirl to create instances of all 3 models?

**Comment by mcmire** [comment]
@jemagee Yup, that's right.

**Comment by jemagee** [comment]
@mcmire Thanks.  I thought perhaps there was something else aside from that solution to do, no biggie...still learning the ins and outs of model testing and using shoulda-matchers.

**Comment by mcmire** [comment]
Gotcha. To be fair, I think the bug mentioned in that issue still exists. Usually `validate_uniqueness_of` doesn't require you to create a model beforehand, because it tries to create one automatically. But in this case that step is failing, so you can help it out and work around the bug by creating one beforehand.
