### ISSUE TITLE
Add collection support for validates_length_of

### ISSUE THREAD

**Issue by sbonami** [thoughtbot/shoulda-matchers#985]
Rails allows the length matcher to work with any object that responds to `#length`, including reflections, collections, and enumerables.

Currently, the validates_length_of only validates string values. This breaks when verifying associations or serialized attributes.

I'd be happy to write the code for this if accepted as a feature.

Reference: https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/length.rb#L41
https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_model/validate_length_of_matcher.rb#L370-L380

**Comment by mcmire** [comment]
@sbonami Sure! I've personally never had a need for this, but if it's something you need, then I think it'd make sense that we support this.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
