### ISSUE TITLE
[Feature request] Support custom exception for strict validations

### ISSUE THREAD

**Issue by dsdshcym** [thoughtbot/shoulda-matchers#987]
According to http://guides.rubyonrails.org/active_record_validations.html#strict-validations,
we can define a strict validation like this:
```ruby
class Person < ApplicationRecord
  validates :token, presence: true, uniqueness: true, strict: TokenGenerationException
end
 
Person.new.valid?  # => TokenGenerationException: Token can't be blank
```

But currently, the `validate_presence_of matcher` does not support custom exceptions.
When this test runs, it will not catch the TokenGenerationException and fail.

**Comment by detj** [comment]
I am facing this exact same issue. Support for StrictValidation would be really really awesome.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
