### ISSUE TITLE
with_options on have_db_column_matcher should not ignore incorrect options

### ISSUE THREAD

**Issue by pirj** [thoughtbot/shoulda-matchers#988]
E.g.

```
      is_expected.to have_db_column(:status).
        with_options(default: 0, nullable: false)
```

Have you spotted the error?
Idea is to fail the test when an option passed is not amongst available options.

**Comment by mcmire** [comment]
@pirj Sure, that would make sense. Now that I look at this again, I'm actually thinking of deprecating this matcher. Honestly, I have never used it, and I don't see much of a need for it since columns are usually implicitly tested by other things such as feature tests, model tests, or things of that nature. Do you have any thoughts about this?

**Comment by pirj** [comment]
@mcmire A single row (ok, few rows with `with_options`) is a concise way to describe model attribute expectations. Tests on default creation are factory tests and are prone to false positives if someone changes the factory to set column to default value (in the example above `status` to 0), even if DB default is `null`, and tests using factories will pass while it will be blowing up when creating real records.

**Comment by mcmire** [comment]
@pirj But this information is already contained in your database, is it not? If you or other developers on your team want to know what columns a table has or what the default value is for a particular column, then everything is all laid in the schema. I guess I don't understand how a test could still pass if someone changes a value in the factories. Could you give an example?

**Comment by pirj** [comment]
Information about program behavior is already in the code, isn't it? But people still write tests anyway.

```
factory :user do
  first_name 'John'
  email 'a@b.c'
end

...

it { user.save! } # Passes

...

> User.new.save!
COMMIT

...

$ RAILS_ENV=test rake db:migrate
 == RunnFirstNameNotNull: migrating

...

it { user.save! } # Passes

...

> User.new.save!
ROLLBACK
```

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
