### ISSUE TITLE
validate_uniqueness_of in rails 5 model test.

### ISSUE THREAD

**Issue by zw963** [thoughtbot/shoulda-matchers#990]
Following is a example

user.rb
```rb
validates :number, uniqueness: true
```

user_test.rb
```rb
class UserTest < ActiveSupport::TestCase
  context 'validate uniqueness' do
    subject { build(:user) }
    should validate_uniqueness_of(:number)
  end
end
```

When I run test:

```sh
Failure:
UserTest#test_: validate uniqueness should require case sensitive unique value for number.  [/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/shoulda-context-1.2.2/lib/shoulda/context/context.rb:346]:
Expected errors to include " “54351533” 已被占用" when number is set to 0,
got no errors
```

Version:

```sh
 ╰─ $ bundle list |grep shoulda
  * shoulda (3.5.0)
  * shoulda-context (1.2.2)
  * shoulda-matchers (2.8.0)
```

Rails version 5.0.0.1
Ruby version 2.2.4

Thanks

**Comment by mcmire** [comment]
You're probably seeing a bug in 2.8.0. I need to update shoulda so that it brings in shoulda-matchers 3 instead of 2.x, and I just haven't done that yet.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
