### ISSUE TITLE
Misleading message from RSpec on validate_length_of

### ISSUE THREAD

**Issue by ledestin** [thoughtbot/shoulda-matchers#994]
I'm trying to check that a length validation isn't present with:
```
it "doesn't validate password length" do
    expect(fresh_user).not_to validate_length_of(:password)               
end
```

And I get the message `Expected User not to validate that the length of :password, but it did.`. If I use `validate_length_of(:password).is_at_least(8)`, it works well, and the test passes.

It seems to me that the message is misleading, and it should instead say that the matcher can't be used without a qualifier like `is_at_least`.

Thanks.

**Comment by mcmire** [comment]
Yup, this seems like a reasonable request to me 👍

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
